"""Generate a typed schema module from annotated table classes.

Pyright has no plugin interface, so the only way a standard editor can check
string column names is for the literal types to exist in real annotations.
This module writes those annotations from the table classes the user already
maintains.

The generator parses the input module with :mod:`ast`. It never imports or
executes it, and it never connects to a database.

The output is one self-contained module: the table classes, a schema class to
pass to ``Database``, one query class per table for single-table queries, and a
generic query class for joined queries. Result rows are ``pysely.Row`` cons
lists, so no row code is generated. The typed classes carry one overload per
column and live under ``TYPE_CHECKING``; a slim runtime copy of each class sits
beside them so import time does not grow with the schema.
"""

from __future__ import annotations

import ast
import re
from collections.abc import Callable
from dataclasses import dataclass
from typing import TypeAlias

_SINGLE_QUOTED = re.compile(r"'([^'\"\\]*)'")

LINE_LENGTH = 88

# Names the generated module defines itself, so the schema cannot use them.
RESERVED_NAMES = frozenset(
    {
        "DatabaseClient",
        "DatabaseExpressionBuilder",
        "DatabaseQuery",
        "SingleTableQuery",
        "TableName",
        "schema",
    }
)

# How many selected fields back an order_by() alias may sit.
ORDER_DEPTH = 8

COMPARE = 'Literal["=", "!=", "<>", "<", "<=", ">", ">="]'
NULL_TEST = 'Literal["is", "is not"]'
PATTERN = 'Literal["like", "not like"]'
COLLECTION = 'Literal["in", "not in"]'

HEADER = '''"""Generated by `pysely codegen` from {source}. Do not edit.

This module is your typed schema. Pass `schema` to `Database`:

    from pysely import Database
    from {module} import schema

    db = Database(schema=schema, dialect=dialect)

Regenerate with:

    pysely codegen {source} \\
        --output {output}
"""'''


class SchemaError(ValueError):
    """Raised when a schema module cannot be turned into a typed interface."""


# --- schema model -----------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Column:
    name: str
    annotation: str
    """The annotation as written, with double quotes."""
    value: str
    """The annotation without ``None``: what comparisons bind."""
    nullable: bool


@dataclass(frozen=True, slots=True)
class Table:
    attribute: str
    class_name: str
    alias: str
    """Prefix of the generated names: ``PersonColumns``, ``PersonQuery``..."""
    columns: tuple[Column, ...]

    @property
    def columns_alias(self) -> str:
        return f"{self.alias}Columns"

    @property
    def scope_alias(self) -> str:
        return f"{self.alias}Scope"

    @property
    def query_class(self) -> str:
        return f"{self.alias}Query"

    @property
    def token(self) -> str:
        return f'Literal["{self.attribute}"]'


@dataclass(frozen=True, slots=True)
class SchemaModel:
    database: str
    tables: tuple[Table, ...]
    imports: tuple[str, ...]
    body: tuple[str, ...]
    """Every top-level statement that is not an import, re-rendered as source."""

    def shared(self, column: str) -> bool:
        """Whether another table also declares this column name."""
        return (
            sum(
                any(item.name == column for item in other.columns)
                for other in self.tables
            )
            > 1
        )

    def spellings(self, table: Table, column: str) -> list[str]:
        """Every way to write a column while its table is the only one in scope."""
        return [f"{table.attribute}.{column}", column]

    def references(self, table: Table, column: str) -> list[str]:
        """Spellings that stay unambiguous after a join: qualified, bare when unique."""
        names = [f"{table.attribute}.{column}"]
        if not self.shared(column):
            names.append(column)
        return names

    def column_literals(self, table: Table) -> list[str]:
        """All spellings for a single-table query, qualified names first."""
        return [f"{table.attribute}.{column.name}" for column in table.columns] + [
            column.name for column in table.columns
        ]

    def scope_literals(self, table: Table) -> list[str]:
        """The spellings a table contributes to a multi-table scope."""
        references = [self.references(table, column.name) for column in table.columns]
        return [names[0] for names in references] + [
            names[1] for names in references if len(names) > 1
        ]


# --- annotation analysis ----------------------------------------------------


def _annotation(node: ast.expr) -> str:
    """Unparse an annotation using the double quotes ruff format expects."""
    return _SINGLE_QUOTED.sub(r'"\1"', ast.unparse(node))


def _is_none(node: ast.expr) -> bool:
    return isinstance(node, ast.Constant) and node.value is None


def _strip_none(node: ast.expr) -> tuple[ast.expr, bool]:
    """Split ``X | None``, ``Optional[X]`` and ``Union[X, None]`` into X."""
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
        left, left_null = _strip_none(node.left)
        right, right_null = _strip_none(node.right)
        if _is_none(node.left):
            return right, True
        if _is_none(node.right):
            return left, True
        if left_null or right_null:
            return ast.BinOp(left, ast.BitOr(), right), True
        return node, False
    if isinstance(node, ast.Subscript):
        head = node.value
        name = head.id if isinstance(head, ast.Name) else getattr(head, "attr", "")
        if name == "Optional":
            inner, _ = _strip_none(node.slice)
            return inner, True
        if name == "Union":
            items = list(node.slice.elts) if isinstance(node.slice, ast.Tuple) else []
            kept = [item for item in items if not _is_none(item)]
            if items and len(kept) < len(items):
                if len(kept) == 1:
                    return kept[0], True
                return ast.Subscript(
                    head, ast.Tuple(kept, ast.Load()), ast.Load()
                ), True
    return node, False


def _nullable(value: str) -> str:
    return f"{value} | None"


def _string_like(value: str) -> bool:
    if value in {"str", "LiteralString"}:
        return True
    if value.startswith("Literal["):
        return all(
            item.strip().startswith('"')
            for item in value[len("Literal[") : -1].split(",")
        )
    return False


# --- parsing ----------------------------------------------------------------


def parse_schema(source: str, *, filename: str = "tables.py") -> SchemaModel:
    """Read annotated classes out of a schema module."""
    tree = ast.parse(source, filename=filename)
    imports = tuple(
        ast.unparse(node)
        for node in tree.body
        if isinstance(node, ast.Import | ast.ImportFrom)
        and not (isinstance(node, ast.ImportFrom) and node.module == "__future__")
    )
    classes: dict[str, dict[str, ast.expr]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        fields: dict[str, ast.expr] = {}
        for item in node.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                fields[item.target.id] = item.annotation
        classes[node.name] = fields

    def names_class(annotation: ast.expr) -> bool:
        return isinstance(annotation, ast.Name) and annotation.id in classes

    database = next(
        (
            name
            for name, fields in classes.items()
            if fields and all(names_class(value) for value in fields.values())
        ),
        None,
    )
    if database is None:
        raise SchemaError(
            "No database class found: expected a class whose annotations are all "
            "other classes in the same module"
        )
    taken = RESERVED_NAMES & set(classes)
    if taken:
        names = ", ".join(sorted(taken))
        raise SchemaError(
            f"Schema class name reserved by the generated module: {names}. "
            "Rename it (for example DatabaseSchema)."
        )
    tables: list[Table] = []
    for attribute, class_ref in classes[database].items():
        class_name = class_ref.id if isinstance(class_ref, ast.Name) else ""
        columns = classes[class_name]
        if not columns:
            raise SchemaError(f"Table class {class_name} has no annotated columns")
        parsed: list[Column] = []
        for name, annotation in columns.items():
            value, nullable = _strip_none(annotation)
            parsed.append(
                Column(name, _annotation(annotation), _annotation(value), nullable)
            )
        tables.append(
            Table(
                attribute=attribute,
                class_name=class_name,
                alias=class_name.removesuffix("Table"),
                columns=tuple(parsed),
            )
        )
    if not tables:
        raise SchemaError(f"Database class {database} declares no tables")
    body = tuple(
        _SINGLE_QUOTED.sub(r'"\1"', ast.unparse(node))
        for node in tree.body
        if not isinstance(node, ast.Import | ast.ImportFrom)
        and not (isinstance(node, ast.ClassDef) and node.name == database)
    )
    return SchemaModel(
        database=database, tables=tuple(tables), imports=imports, body=body
    )


# --- rendering helpers ------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Sub:
    """A subscripted type expression, rendered the way ruff format would."""

    name: str
    args: tuple[TypeExpr, ...]


TypeExpr: TypeAlias = "str | Sub | Union"


def _one_line(expr: TypeExpr) -> str:
    if isinstance(expr, str):
        return expr
    if isinstance(expr, Union):
        return " | ".join(_one_line(item) for item in expr.items)
    return f"{expr.name}[{', '.join(_one_line(arg) for arg in expr.args)}]"


def _render_type(expr: TypeExpr, indent: int, *, first: int, last: int) -> list[str]:
    """Render a type; ``first``/``last`` are the widths already used around it."""
    single = _one_line(expr)
    if isinstance(expr, str) or first + len(single) + last <= LINE_LENGTH:
        return [single]
    if isinstance(expr, Union):
        # ruff splits a long union one member per line, leading with `|`.
        pad = " " * indent
        lines = _render_type(expr.items[0], indent, first=first, last=0)
        for position, item in enumerate(expr.items[1:], start=2):
            width = last if position == len(expr.items) else 0
            rendered = _render_type(item, indent, first=indent + 2, last=width)
            lines.append(f"{pad}| {rendered[0]}")
            lines.extend(rendered[1:])
        return lines
    pad = " " * indent
    inner = " " * (indent + 4)
    joined = ", ".join(_one_line(arg) for arg in expr.args)
    if len(inner) + len(joined) <= LINE_LENGTH:
        return [f"{expr.name}[", f"{inner}{joined}", f"{pad}]"]
    lines = [f"{expr.name}["]
    for arg in expr.args:
        rendered = _render_type(arg, indent + 4, first=len(inner), last=1)
        rendered[-1] += ","
        lines.append(f"{inner}{rendered[0]}")
        lines.extend(rendered[1:])
    lines.append(f"{pad}]")
    return lines


def _literal(names: list[str]) -> Sub:
    return Sub("Literal", tuple(f'"{name}"' for name in names))


@dataclass(frozen=True, slots=True)
class Union:
    """``a | b | Sub[...]``: only a trailing subscript is ever broken."""

    items: tuple[TypeExpr, ...]


def _signature(
    name: str,
    parameters: list[tuple[str, TypeExpr | None]],
    returns: TypeExpr,
    indent: int = 4,
    body: str = " ...",
) -> list[str]:
    """Render ``def name(params) -> returns:`` the way ruff format would."""
    pad = " " * indent
    params = [
        f"{param}: {_one_line(annotation)}" if annotation is not None else param
        for param, annotation in parameters
    ]
    single = f"{pad}def {name}({', '.join(params)}) -> {_one_line(returns)}:{body}"
    if len(single) <= LINE_LENGTH:
        return [single]
    lines = [f"{pad}def {name}("]
    inner = " " * (indent + 4)
    joined = ", ".join(params)
    if len(inner) + len(joined) <= LINE_LENGTH:
        lines.append(f"{inner}{joined}")
    else:
        for param, annotation in parameters:
            if annotation is None:
                lines.append(f"{inner}{param},")
                continue
            rendered = _render_type(
                annotation, indent + 4, first=len(inner) + len(param) + 2, last=1
            )
            rendered[-1] += ","
            lines.append(f"{inner}{param}: {rendered[0]}")
            lines.extend(rendered[1:])
    tail = _render_type(returns, indent, first=len(pad) + 5, last=1 + len(body))
    lines.append(f"{pad}) -> {tail[0]}" + (f":{body}" if len(tail) == 1 else ""))
    if len(tail) > 1:
        lines.extend(tail[1:-1])
        lines.append(f"{tail[-1]}:{body}")
    return lines


def _class_header(name: str, bases: list[TypeExpr], indent: int) -> list[str]:
    """Render ``class Name(bases):`` the way ruff format would."""
    pad = " " * indent
    joined = ", ".join(_one_line(base) for base in bases)
    single = f"{pad}class {name}({joined}):"
    if len(single) <= LINE_LENGTH:
        return [single]
    inner = " " * (indent + 4)
    if len(inner) + len(joined) <= LINE_LENGTH:
        return [f"{pad}class {name}(", f"{inner}{joined}", f"{pad}):"]
    lines = [f"{pad}class {name}("]
    for base in bases:
        rendered = _render_type(base, indent + 4, first=len(inner), last=1)
        rendered[-1] += ","
        lines.append(f"{inner}{rendered[0]}")
        lines.extend(rendered[1:])
    lines.append(f"{pad}):")
    return lines


def _import_order(name: str) -> tuple[int, str]:
    """isort's default order-by-type: CONSTANTS, then Classes, then functions."""
    if name.isupper():
        return (0, name)
    if name[:1].isupper():
        return (1, name)
    return (2, name)


# --- rendering --------------------------------------------------------------


class _Renderer:
    def __init__(self, model: SchemaModel) -> None:
        self.model = model
        self.lines: list[str] = []

    # --- helpers

    def emit(self, lines: list[str]) -> None:
        self.lines.extend(lines)

    def overload(
        self,
        name: str,
        parameters: list[tuple[str, TypeExpr | None]],
        returns: TypeExpr,
        indent: int = 8,
    ) -> None:
        pad = " " * indent
        self.emit([f"{pad}@overload"])
        self.emit(_signature(name, parameters, returns, indent))
        self.emit([""])

    @staticmethod
    def joined(
        tables: str, columns: str, null: str, fields: TypeExpr, star: str
    ) -> Sub:
        return Sub("DatabaseQuery", (tables, columns, null, fields, star))

    @staticmethod
    def cons(key: str, value: str, rest: str = "FieldsT") -> Sub:
        return Sub("Cons", (key, value, rest))

    @staticmethod
    def fields_pattern(depth: int) -> Sub:
        """``Cons[K1, V1, Cons[K2, V2, ... RestT]]`` naming every position."""
        inner: TypeExpr = "RestT"
        for position in range(depth, 0, -1):
            inner = Sub("Cons", (f"K{position}", f"V{position}", inner))
        assert isinstance(inner, Sub)
        return inner

    def ordering(self, query: Callable[[TypeExpr], Sub], columns: str) -> None:
        """order_by: a column in scope, or the alias of a selected field."""
        self.overload(
            "order_by",
            [
                ("self", None),
                ("column", columns),
                ('direction: OrderDirection = "asc"', None),
            ],
            query("FieldsT"),
        )
        for depth in range(1, ORDER_DEPTH + 1):
            pattern = self.fields_pattern(depth)
            self.overload(
                "order_by",
                [
                    ("self", query(pattern)),
                    ("column", f"K{depth}"),
                    ('direction: OrderDirection = "asc"', None),
                ],
                query(pattern),
            )
        self.emit(
            [
                "        def order_by(self, column: Any, direction: Any = "
                '"asc") -> Any:',
                "            return self._order_by(column, direction)",
                "",
            ]
        )

    def having(self, query: Sub, builder: str) -> None:
        """having: callback form only, to stay under pyright's per-module
        definition ceiling; the builder carries the typed operator shapes."""
        self.emit(
            _signature(
                "having",
                [
                    ("self", None),
                    (
                        "column",
                        Sub("Callable", (Sub("", (builder,)), "Expression[bool]")),
                    ),
                ],
                query,
                8,
                body="",
            )
        )
        self.emit(["            return self._having(cast(Any, column))", ""])

    def shapes(
        self, table: Table, names_for: Callable[[Column], list[str]]
    ) -> list[tuple[list[str], str, TypeExpr]]:
        """(column names, operator literal, value type) for each where overload."""
        by_value: dict[str, list[str]] = {}
        all_names: list[str] = []
        for column in table.columns:
            names = names_for(column)
            by_value.setdefault(column.value, []).extend(names)
            all_names.extend(names)
        shapes: list[tuple[list[str], str, TypeExpr]] = []
        for value, names in by_value.items():
            shapes.append((names, COMPARE, value))
            shapes.append(
                (
                    names,
                    COLLECTION,
                    Union((Sub("list", (value,)), Sub("tuple", (value, "...")))),
                )
            )
            if _string_like(value):
                shapes.append((names, PATTERN, "str"))
        shapes.append((all_names, NULL_TEST, "None"))
        return shapes

    def scope_names(self, table: Table) -> Callable[[Column], list[str]]:
        return lambda column: self.model.references(table, column.name)

    def all_names(self, table: Table) -> Callable[[Column], list[str]]:
        return lambda column: self.model.spellings(table, column.name)

    def by_value(
        self, table: Table, names_for: Callable[[Column], list[str]]
    ) -> dict[tuple[str, bool], list[str]]:
        groups: dict[tuple[str, bool], list[str]] = {}
        for column in table.columns:
            groups.setdefault((column.value, column.nullable), []).extend(
                names_for(column)
            )
        return groups

    # --- sections

    def render(self, *, source: str, output: str) -> str:
        model = self.model
        module = output.rsplit("/", 1)[-1].removesuffix(".py")
        header = HEADER.format(
            source=source, output=output, module=module, schema=model.database
        )
        self.emit(
            [
                header,
                "",
                "# The typed classes overload every public method per column, so",
                "# the checks below are noise for generated code.",
                '# mypy: disable-error-code="override, overload-overlap"',
                "# pyright: reportIncompatibleMethodOverride=false",
                "# pyright: reportOverlappingOverload=false",
                "",
                "from __future__ import annotations",
                "",
            ]
        )
        self.imports()
        self.emit(
            [
                "",
                "from pysely import (",
                "    Cons,",
                "    Expression,",
                "    ExpressionBuilder,",
                "    GeneratedSchema,",
                "    Nil,",
                "    OrderDirection,",
                "    Pysely,",
                "    TypedSchemaQueryBuilder,",
                ")",
                "",
                "",
                f"# Table classes, copied from {source}.",
            ]
        )
        for statement in model.body:
            self.emit([statement, "", ""])
        self.aliases()
        self.emit(["", "if TYPE_CHECKING:"])
        self.joined_builder()
        self.joined_query()
        self.single_table_base()
        for table in model.tables:
            self.table_query(table)
        self.client_class()
        self.emit(["else:"])
        self.runtime_classes()
        self.emit(
            [
                "",
                "",
                "# Schema class. Pass it to `Database`; its base names the client.",
                f"class {model.database}(GeneratedSchema[DatabaseClient]):",
            ]
        )
        self.emit(
            [f"    {table.attribute}: {table.class_name}" for table in model.tables]
        )
        self.emit(["", "", f"schema = {model.database}", ""])
        return "\n".join(self.lines)

    def imports(self) -> None:
        typing_names = {
            "TYPE_CHECKING",
            "Any",
            "Generic",
            "Literal",
            "LiteralString",
            "Never",
            "TypeAlias",
            "TypeVar",
            "cast",
            "overload",
        }
        standard: list[tuple[str, list[str]]] = [
            ("collections.abc", ["from collections.abc import Callable, Sequence"]),
        ]
        for item in self.model.imports:
            module = item.split()[1]
            if item.startswith("from typing import "):
                imported = item.removeprefix("from typing import ")
                typing_names.update(name.strip() for name in imported.split(","))
            else:
                standard.append((module, [item]))
        standard.append(
            (
                "typing",
                [
                    "from typing import (",
                    *[
                        f"    {name},"
                        for name in sorted(typing_names, key=_import_order)
                    ],
                    ")",
                ],
            )
        )
        for _, block in sorted(standard, key=lambda entry: entry[0]):
            self.emit(block)

    def aliases(self) -> None:
        model = self.model
        self.emit(
            [
                "# XColumns: every spelling, valid while X is the only table in the",
                "# query. XScope: the spellings that stay unambiguous after a join.",
            ]
        )
        for table in model.tables:
            for name, names in (
                (table.columns_alias, model.column_literals(table)),
                (table.scope_alias, model.scope_literals(table)),
            ):
                self.emit([f"{name}: TypeAlias = Literal["])
                self.emit([f'    "{item}",' for item in names])
                self.emit(["]"])
        table_names = [table.attribute for table in model.tables]
        self.emit(
            [
                f"TableName: TypeAlias = {_one_line(_literal(table_names))}",
                "",
                "# Query state: tables joined, columns in scope, tables joined",
                "# nullably, selected fields (newest first), and whether a right or",
                "# full join made every field nullable.",
                'TableT = TypeVar("TableT", bound=str)',
                'TablesT = TypeVar("TablesT", bound=str)',
                'ColumnsT = TypeVar("ColumnsT", bound=str)',
                'ColumnT = TypeVar("ColumnT", bound=str)',
                'ScopeT = TypeVar("ScopeT", bound=str)',
                'NullT = TypeVar("NullT", bound=str)',
                'FieldsT = TypeVar("FieldsT")',
                'StarT = TypeVar("StarT", bound=str)',
                'AliasT = TypeVar("AliasT", bound=LiteralString | Literal[""])',
                "# Positions in the selected-field list, for ordering by an alias.",
                'RestT = TypeVar("RestT")',
            ]
        )
        self.emit(
            [
                f'K{depth} = TypeVar("K{depth}", bound=str)'
                for depth in range(1, ORDER_DEPTH + 1)
            ]
            + [f'V{depth} = TypeVar("V{depth}")' for depth in range(1, ORDER_DEPTH + 1)]
        )

    # --- expression builders

    def builder_impl(self) -> None:
        self.emit(
            _signature(
                "__call__",
                [
                    ("self", None),
                    ("column", "Any"),
                    ("operator", "Any"),
                    ("value", "Any"),
                ],
                "Expression[bool]",
                8,
                body="",
            )
        )
        self.emit(["            return super().__call__(column, operator, value)", ""])

    def joined_builder(self) -> None:
        self.emit(
            [
                "    # Callback predicates get the same scope and value checks as a",
                "    # flat where() call.",
                "    class DatabaseExpressionBuilder(",
                "        ExpressionBuilder[ColumnT], Generic[TablesT, ColumnT]",
                "    ):",
            ]
        )
        for table in self.model.tables:
            # Bare names shared with other tables are valid while this table is
            # alone in the query: an exact-scope overload set for just those.
            shared = [c for c in table.columns if self.model.shared(c.name)]
            if shared:
                exact = Sub(
                    "DatabaseExpressionBuilder", (table.token, table.columns_alias)
                )
                subset = Table(
                    table.attribute, table.class_name, table.alias, tuple(shared)
                )
                for names, operator, value in self.shapes(
                    subset, lambda column: [column.name]
                ):
                    self.overload(
                        "__call__",
                        [
                            ("self", exact),
                            ("column", _literal(names)),
                            ("operator", operator),
                            ("value", value),
                        ],
                        "Expression[bool]",
                    )
            receiver = Sub(
                "DatabaseExpressionBuilder", (f"TablesT | {table.token}", "ColumnT")
            )
            for names, operator, value in self.shapes(table, self.scope_names(table)):
                self.overload(
                    "__call__",
                    [
                        ("self", receiver),
                        ("column", _literal(names)),
                        ("operator", operator),
                        ("value", value),
                    ],
                    "Expression[bool]",
                )
        self.builder_impl()

    def select_impls(self) -> None:
        self.emit(
            [
                "        def select(self, selections: Any) -> Any:",
                "            return super().select(selections)",
                "",
            ]
        )

    def joined_query(self) -> None:
        model = self.model
        self.emit(
            [
                "    # Joined queries. One overload per column; the nullable form",
                "    # comes first and only matches once its table is outer-joined.",
                "    class DatabaseQuery(",
                f'        TypedSchemaQueryBuilder["{model.database}", ColumnT, '
                "FieldsT, StarT],",
                "        Generic[TablesT, ColumnT, NullT, FieldsT, StarT],",
                "    ):",
            ]
        )
        for table in model.tables:
            tables = f"TablesT | {table.token}"
            nullable = f"NullT | {table.token}"
            for column in table.columns:
                selections = _literal(model.references(table, column.name))
                key = f'Literal["{column.name}"]'
                for null, value in (
                    (nullable, _nullable(column.value)),
                    ("NullT", column.annotation),
                ):
                    self.overload(
                        "select",
                        [
                            (
                                "self",
                                self.joined(
                                    tables, "ColumnT", null, "FieldsT", "StarT"
                                ),
                            ),
                            ("selections", selections),
                        ],
                        self.joined(
                            tables, "ColumnT", null, self.cons(key, value), "StarT"
                        ),
                    )
        self.overload(
            "select",
            [("self", None), ("selections", "ColumnT | Sequence[ColumnT]")],
            self.joined(
                "TablesT", "ColumnT", "NullT", self.cons("str", "object"), "StarT"
            ),
        )
        self.select_impls()
        self.emit(
            ["        # select_as: grouped by value type; the alias becomes a key."]
        )
        for table in model.tables:
            tables = f"TablesT | {table.token}"
            nullable = f"NullT | {table.token}"
            for (value, is_nullable), names in self.by_value(
                table, self.scope_names(table)
            ).items():
                plain = _nullable(value) if is_nullable else value
                for null, read in ((nullable, _nullable(value)), ("NullT", plain)):
                    self.overload(
                        "select_as",
                        [
                            (
                                "self",
                                self.joined(
                                    tables, "ColumnT", null, "FieldsT", "StarT"
                                ),
                            ),
                            ("source", _literal(names)),
                            ("alias", "AliasT"),
                        ],
                        self.joined(
                            tables, "ColumnT", null, self.cons("AliasT", read), "StarT"
                        ),
                    )
        self.overload(
            "select_as",
            [("self", None), ("source", "ColumnT"), ("alias", "str")],
            self.joined(
                "TablesT", "ColumnT", "NullT", self.cons("str", "object"), "StarT"
            ),
        )
        self.emit(
            [
                "        def select_as(self, source: Any, alias: str) -> Any:",
                "            return self._select_as(source, alias)",
                "",
                "        # where: operator families take different value shapes.",
            ]
        )
        for table in model.tables:
            tables = f"TablesT | {table.token}"
            query = self.joined(tables, "ColumnT", "NullT", "FieldsT", "StarT")
            for names, operator, shape in self.shapes(table, self.scope_names(table)):
                self.overload(
                    "where",
                    [
                        ("self", query),
                        ("column", _literal(names)),
                        ("operator", operator),
                        ("value", shape),
                    ],
                    query,
                )
        self.overload(
            "where",
            [
                ("self", None),
                (
                    "column",
                    Sub(
                        "Callable",
                        (
                            Sub("", ("DatabaseExpressionBuilder[TablesT, ColumnT]",)),
                            "Expression[bool]",
                        ),
                    ),
                ),
            ],
            self.joined("TablesT", "ColumnT", "NullT", "FieldsT", "StarT"),
        )
        self.where_impl()
        self.having(
            self.joined("TablesT", "ColumnT", "NullT", "FieldsT", "StarT"),
            "DatabaseExpressionBuilder[TablesT, ColumnT]",
        )
        self.ordering(
            lambda fields: self.joined("TablesT", "ColumnT", "NullT", fields, "StarT"),
            "ColumnT",
        )
        self.emit(
            [
                "        # joins: the ON columns may use the prior scope and the new",
                "        # table. Outer joins record which side may be missing.",
            ]
        )
        for kind in ("inner", "left", "right", "full"):
            for table in model.tables:
                self.overload(
                    f"{kind}_join",
                    [
                        ("self", None),
                        ("table", table.token),
                        ("left", f"ColumnT | {table.scope_alias}"),
                        ("right", f"ColumnT | {table.scope_alias}"),
                    ],
                    self.join_result(
                        kind, table, "TablesT", "ColumnT", "NullT", "StarT"
                    ),
                )
            self.join_impl(kind, "DatabaseQuery")

    def join_result(
        self, kind: str, table: Table, tables: str, columns: str, null: str, star: str
    ) -> Sub:
        marked = f"{null} | {table.token}" if null != "Never" else table.token
        return self.joined(
            f"{tables} | {table.token}",
            f"{columns} | {table.scope_alias}",
            marked if kind in {"left", "full"} else null,
            "FieldsT",
            'Literal["*"]' if kind in {"right", "full"} else star,
        )

    def where_impl(self) -> None:
        self.emit(
            _signature(
                "where",
                [
                    ("self", None),
                    ("column", "Any"),
                    ("operator: Any = None", None),
                    ("value: Any = None", None),
                ],
                "Any",
                8,
                body="",
            )
        )
        self.emit(
            [
                "            if isinstance(column, str):",
                "                name = cast(Any, column)",
                "                return super().where(name, operator, value)",
                "            return super().where(column)",
                "",
            ]
        )

    def join_impl(self, kind: str, cls: str) -> None:
        self.emit(
            [
                f"        def {kind}_join(self, table: Any, left: Any, right: Any)"
                " -> Any:",
                f'            return self._join("{kind}", table, left, right)',
                "",
            ]
        )

    def single_table_base(self) -> None:
        model = self.model
        self.emit(
            [
                "    # Single-table queries. Each table gets its own class so the",
                "    # editor only weighs that table's overloads; joins move to",
                "    # DatabaseQuery.",
                "    class SingleTableQuery(",
                f'        TypedSchemaQueryBuilder["{model.database}", ColumnsT, '
                "FieldsT, Never],",
                "        Generic[TableT, ColumnsT, ScopeT, FieldsT],",
                "    ):",
            ]
        )
        for kind in ("inner", "left", "right", "full"):
            for table in model.tables:
                self.overload(
                    f"{kind}_join",
                    [
                        ("self", None),
                        ("table", table.token),
                        ("left", f"ScopeT | {table.scope_alias}"),
                        ("right", f"ScopeT | {table.scope_alias}"),
                    ],
                    self.join_result(kind, table, "TableT", "ScopeT", "Never", "Never"),
                )
            self.emit(
                [
                    f"        def {kind}_join(self, table: Any, left: Any, right: Any)"
                    " -> Any:",
                    "            query = self._query.join("
                    f'"{kind}", table, left, right)',
                    "            joined: DatabaseQuery[Any, Any, Any, Any, Any] = "
                    "DatabaseQuery(",
                    "                cast(Any, query.typed(DatabaseExpressionBuilder))",
                    "            )",
                    "            return joined",
                    "",
                ]
            )

    def table_query(self, table: Table) -> None:
        model = self.model
        cls = table.query_class
        result = Sub(cls, ("FieldsT",))
        self.emit(
            [
                f"    class {cls}(",
                f"        SingleTableQuery[{table.token}, {table.columns_alias}, "
                f"{table.scope_alias}, FieldsT],",
                "        Generic[FieldsT],",
                "    ):",
            ]
        )
        for column in table.columns:
            self.overload(
                "select",
                [
                    ("self", None),
                    ("selections", _literal(model.spellings(table, column.name))),
                ],
                Sub(cls, (self.cons(f'Literal["{column.name}"]', column.annotation),)),
            )
        self.overload(
            "select",
            [
                ("self", None),
                (
                    "selections",
                    f"{table.columns_alias} | Sequence[{table.columns_alias}]",
                ),
            ],
            Sub(cls, (self.cons("str", "object"),)),
        )
        self.select_impls()
        for (value, is_nullable), names in self.by_value(
            table, self.all_names(table)
        ).items():
            read = _nullable(value) if is_nullable else value
            self.overload(
                "select_as",
                [("self", None), ("source", _literal(names)), ("alias", "AliasT")],
                Sub(cls, (self.cons("AliasT", read),)),
            )
        self.overload(
            "select_as",
            [("self", None), ("source", table.columns_alias), ("alias", "str")],
            Sub(cls, (self.cons("str", "object"),)),
        )
        self.emit(
            [
                "        def select_as(self, source: Any, alias: str) -> Any:",
                "            return self._select_as(source, alias)",
                "",
            ]
        )
        for names, operator, shape in self.shapes(table, self.all_names(table)):
            self.overload(
                "where",
                [
                    ("self", None),
                    ("column", _literal(names)),
                    ("operator", operator),
                    ("value", shape),
                ],
                result,
            )
        builder = f"DatabaseExpressionBuilder[{table.token}, {table.columns_alias}]"
        self.overload(
            "where",
            [
                ("self", None),
                ("column", Sub("Callable", (Sub("", (builder,)), "Expression[bool]"))),
            ],
            result,
        )
        self.where_impl()
        self.having(result, builder)
        self.ordering(lambda fields: Sub(cls, (fields,)), table.columns_alias)

    def client_class(self) -> None:
        model = self.model
        self.emit(
            [
                "    # Typed client. `Database(schema=...)` builds and returns this.",
                f'    class DatabaseClient(Pysely["{model.database}"]):',
            ]
        )
        for table in model.tables:
            self.overload(
                "select_from",
                [("self", None), ("table", table.token)],
                Sub(table.query_class, ("Nil",)),
            )
        self.emit(
            [
                "        def select_from(self, table: str) -> Any:",
                "            query = super().select_from(table)",
                "            typed = query.typed(DatabaseExpressionBuilder)",
                "            return _QUERIES[table](cast(Any, typed))",
                "",
            ]
        )

    def runtime_classes(self) -> None:
        model = self.model
        self.emit(
            [
                "    # Runtime twins of the typed classes: no overloads, so importing",
                "    # this module costs the same for any schema size.",
                "    class DatabaseExpressionBuilder(ExpressionBuilder):",
                "        pass",
                "",
                "    class DatabaseQuery(TypedSchemaQueryBuilder):",
                "        def select_as(self, source, alias):",
                "            return self._select_as(source, alias)",
                "",
                "        def having(self, column):",
                "            return self._having(column)",
                "",
                '        def order_by(self, column, direction="asc"):',
                "            return self._order_by(column, direction)",
                "",
            ]
        )
        for kind in ("inner", "left", "right", "full"):
            self.emit(
                [
                    f"        def {kind}_join(self, table, left, right):",
                    f'            return self._join("{kind}", table, left, right)',
                    "",
                ]
            )
        self.emit(
            [
                "    class SingleTableQuery(TypedSchemaQueryBuilder):",
                "        def select_as(self, source, alias):",
                "            return self._select_as(source, alias)",
                "",
                "        def having(self, column):",
                "            return self._having(column)",
                "",
                '        def order_by(self, column, direction="asc"):',
                "            return self._order_by(column, direction)",
                "",
            ]
        )
        for kind in ("inner", "left", "right", "full"):
            self.emit(
                [
                    f"        def {kind}_join(self, table, left, right):",
                    f'            query = self._query.join("{kind}", table, left, '
                    "right)",
                    "            return DatabaseQuery(query.typed("
                    "DatabaseExpressionBuilder))",
                    "",
                ]
            )
        for table in model.tables:
            self.emit(
                [
                    f"    class {table.query_class}(SingleTableQuery):",
                    "        pass",
                    "",
                ]
            )
        self.emit(
            [
                "    class DatabaseClient(Pysely):",
                "        def select_from(self, table):",
                "            query = super().select_from(table)",
                "            typed = query.typed(DatabaseExpressionBuilder)",
                "            return _QUERIES[table](typed)",
                "",
                "",
                "# The single-table query class behind each table name.",
                "_QUERIES: dict[str, type[Any]] = {",
            ]
        )
        self.emit(
            [f'    "{table.attribute}": {table.query_class},' for table in model.tables]
        )
        self.emit(["}"])


# Pyright stops analysing a module whose top-level code flow exceeds its
# complexity limit; empirically that is about 15,000 function definitions.
PYRIGHT_DEFINITION_CEILING = 14_000


def render(
    model: SchemaModel, *, source: str = "tables.py", output: str = "schema.py"
) -> str:
    rendered = _Renderer(model).render(source=source, output=output)
    definitions = sum(
        line.lstrip().startswith("def ") for line in rendered.splitlines()
    )
    if definitions > PYRIGHT_DEFINITION_CEILING:
        raise SchemaError(
            f"{model.database} would need {definitions} typed method definitions; "
            f"Pyright stops analysing a module above about "
            f"{PYRIGHT_DEFINITION_CEILING}. Split the tables across several "
            "database classes (one generated module each), or drop columns "
            "that queries never touch."
        )
    return rendered


def generate(
    source: str, *, source_name: str = "tables.py", output: str = "schema.py"
) -> str:
    """Turn table-class source into typed schema-module source."""
    return render(
        parse_schema(source, filename=source_name), source=source_name, output=output
    )
