"""Generate a typed schema module from annotated table classes.

Pyright has no plugin interface, so the only way a standard editor can check
string column names is for the literal types to exist in real annotations.
This module writes those annotations from the table classes the user already
maintains.

The generator parses the input module with :mod:`ast`. It never imports or
executes it, and it never connects to a database.

The output is one self-contained module: the table classes, a schema class to
pass to ``Database``, and the typed query, row and expression-builder classes.
The typed classes carry one overload per column and live under
``TYPE_CHECKING``; a slim runtime copy of each class sits beside them so import
time does not grow with the schema.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass, field
from typing import TypeAlias

_SINGLE_QUOTED = re.compile(r"'([^'\"\\]*)'")

LINE_LENGTH = 88

# Names the generated module defines itself, so the schema cannot use them.
RESERVED_NAMES = frozenset(
    {
        "DatabaseClient",
        "DatabaseExpressionBuilder",
        "DatabaseQuery",
        "DatabaseRow",
        "TableName",
        "schema",
    }
)

COMPARE = 'Literal["=", "!=", "<>", "<", "<=", ">", ">="]'
NULL_TEST = 'Literal["is", "is not"]'
PATTERN = 'Literal["like", "not like"]'
COLLECTION = 'Literal["in", "not in"]'

HEADER = '''"""Generated by `pysely codegen` from {source}. Do not edit.

This module is your typed schema. Pass `schema` to `Database`:

    from pysely import Database
    from {module} import schema

    db = Database(schema=schema, dialect=dialect)

Regenerate with:

    pysely codegen {source} \\
        --output {output}
"""'''


class SchemaError(ValueError):
    """Raised when a schema module cannot be turned into a typed interface."""


# --- schema model -----------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Column:
    name: str
    annotation: str
    """The annotation as written, with double quotes."""
    value: str
    """The annotation without ``None``: what comparisons bind."""
    nullable: bool


@dataclass(frozen=True, slots=True)
class Table:
    attribute: str
    class_name: str
    alias: str
    """Name of the ``Literal`` alias listing the table's column references."""
    columns: tuple[Column, ...]


@dataclass(frozen=True, slots=True)
class Group:
    """A result-key group: every selected key of one value type."""

    name: str
    value: str
    """Value type read back for a key in this group."""


@dataclass(frozen=True, slots=True)
class SchemaModel:
    database: str
    tables: tuple[Table, ...]
    imports: tuple[str, ...]
    body: tuple[str, ...]
    """Every top-level statement that is not an import, re-rendered as source."""
    groups: tuple[Group, ...] = field(default=())
    """Key groups in order, ending with the ``object`` fallback."""

    def shared(self, column: str) -> bool:
        """Whether another table also declares this column name."""
        return (
            sum(
                any(item.name == column for item in other.columns)
                for other in self.tables
            )
            > 1
        )

    def references(self, table: Table, column: str) -> list[str]:
        """Names that resolve to a column in any scope: qualified, bare when unique."""
        names = [f"{table.attribute}.{column}"]
        if not self.shared(column):
            names.append(column)
        return names

    def column_literals(self, table: Table) -> list[str]:
        """Every name in scope for a table, qualified names first."""
        references = [self.references(table, column.name) for column in table.columns]
        return [names[0] for names in references] + [
            names[1] for names in references if len(names) > 1
        ]

    def group(self, value: str, nullable: bool) -> Group:
        wanted = _nullable(value) if nullable else value
        for group in self.groups:
            if group.value == wanted:
                return group
        raise KeyError(wanted)  # pragma: no cover - groups cover every column


# --- annotation analysis ----------------------------------------------------


def _annotation(node: ast.expr) -> str:
    """Unparse an annotation using the double quotes ruff format expects."""
    return _SINGLE_QUOTED.sub(r'"\1"', ast.unparse(node))


def _is_none(node: ast.expr) -> bool:
    return isinstance(node, ast.Constant) and node.value is None


def _strip_none(node: ast.expr) -> tuple[ast.expr, bool]:
    """Split ``X | None``, ``Optional[X]`` and ``Union[X, None]`` into X."""
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
        left, left_null = _strip_none(node.left)
        right, right_null = _strip_none(node.right)
        if _is_none(node.left):
            return right, True
        if _is_none(node.right):
            return left, True
        if left_null or right_null:
            return ast.BinOp(left, ast.BitOr(), right), True
        return node, False
    if isinstance(node, ast.Subscript):
        head = node.value
        name = head.id if isinstance(head, ast.Name) else getattr(head, "attr", "")
        if name == "Optional":
            inner, _ = _strip_none(node.slice)
            return inner, True
        if name == "Union":
            items = list(node.slice.elts) if isinstance(node.slice, ast.Tuple) else []
            kept = [item for item in items if not _is_none(item)]
            if items and len(kept) < len(items):
                if len(kept) == 1:
                    return kept[0], True
                return ast.Subscript(
                    head, ast.Tuple(kept, ast.Load()), ast.Load()
                ), True
    return node, False


def _nullable(value: str) -> str:
    return f"{value} | None"


def _string_like(value: str) -> bool:
    if value in {"str", "LiteralString"}:
        return True
    if value.startswith("Literal["):
        return all(
            item.strip().startswith('"')
            for item in value[len("Literal[") : -1].split(",")
        )
    return False


def _group_base_name(value: str, column: str) -> str:
    if value.startswith("Literal["):
        words = re.findall(r"[A-Za-z0-9]+", column)
    else:
        words = re.findall(r"[A-Za-z0-9]+", value)
    return "".join(word[:1].upper() + word[1:] for word in words) or "Value"


# --- parsing ----------------------------------------------------------------


def parse_schema(source: str, *, filename: str = "tables.py") -> SchemaModel:
    """Read annotated classes out of a schema module."""
    tree = ast.parse(source, filename=filename)
    imports = tuple(
        ast.unparse(node)
        for node in tree.body
        if isinstance(node, ast.Import | ast.ImportFrom)
        and not (isinstance(node, ast.ImportFrom) and node.module == "__future__")
    )
    classes: dict[str, dict[str, ast.expr]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        fields: dict[str, ast.expr] = {}
        for item in node.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                fields[item.target.id] = item.annotation
        classes[node.name] = fields

    def names_class(annotation: ast.expr) -> bool:
        return isinstance(annotation, ast.Name) and annotation.id in classes

    database = next(
        (
            name
            for name, fields in classes.items()
            if fields and all(names_class(value) for value in fields.values())
        ),
        None,
    )
    if database is None:
        raise SchemaError(
            "No database class found: expected a class whose annotations are all "
            "other classes in the same module"
        )
    taken = RESERVED_NAMES & set(classes)
    if taken:
        names = ", ".join(sorted(taken))
        raise SchemaError(
            f"Schema class name reserved by the generated module: {names}. "
            "Rename it (for example DatabaseSchema)."
        )
    tables: list[Table] = []
    for attribute, class_ref in classes[database].items():
        class_name = class_ref.id if isinstance(class_ref, ast.Name) else ""
        columns = classes[class_name]
        if not columns:
            raise SchemaError(f"Table class {class_name} has no annotated columns")
        parsed: list[Column] = []
        for name, annotation in columns.items():
            value, nullable = _strip_none(annotation)
            parsed.append(
                Column(name, _annotation(annotation), _annotation(value), nullable)
            )
        tables.append(
            Table(
                attribute=attribute,
                class_name=class_name,
                alias=f"{class_name.removesuffix('Table')}Columns",
                columns=tuple(parsed),
            )
        )
    if not tables:
        raise SchemaError(f"Database class {database} declares no tables")
    body = tuple(
        _SINGLE_QUOTED.sub(r'"\1"', ast.unparse(node))
        for node in tree.body
        if not isinstance(node, ast.Import | ast.ImportFrom)
        and not (isinstance(node, ast.ClassDef) and node.name == database)
    )
    model = SchemaModel(
        database=database, tables=tuple(tables), imports=imports, body=body
    )
    return SchemaModel(
        database=database,
        tables=tuple(tables),
        imports=imports,
        body=body,
        groups=_groups(model),
    )


def _groups(model: SchemaModel) -> tuple[Group, ...]:
    """One key group per value type, plus its nullable form for outer joins."""
    groups: list[Group] = []
    used: set[str] = set()
    values: set[str] = set()

    def add(value: str, base: str) -> None:
        if value in values:
            return
        values.add(value)
        name = base
        counter = 2
        while f"{name}Keys" in used or name in RESERVED_NAMES:
            name = f"{base}{counter}"
            counter += 1
        used.add(f"{name}Keys")
        groups.append(Group(f"{name}Keys", value))

    for table in model.tables:
        for column in table.columns:
            base = _group_base_name(column.value, column.name)
            add(column.value, base)
            add(_nullable(column.value), f"Opt{base}")
    add("object", "Object")
    return tuple(groups)


# --- rendering helpers ------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Sub:
    """A subscripted type expression, rendered the way ruff format would."""

    name: str
    args: tuple[TypeExpr, ...]


TypeExpr: TypeAlias = "str | Sub | Union"


def _one_line(expr: TypeExpr) -> str:
    if isinstance(expr, str):
        return expr
    if isinstance(expr, Union):
        return " | ".join(_one_line(item) for item in expr.items)
    return f"{expr.name}[{', '.join(_one_line(arg) for arg in expr.args)}]"


def _render_type(expr: TypeExpr, indent: int, *, first: int, last: int) -> list[str]:
    """Render a type; ``first``/``last`` are the widths already used around it."""
    single = _one_line(expr)
    if isinstance(expr, str) or first + len(single) + last <= LINE_LENGTH:
        return [single]
    if isinstance(expr, Union):
        # ruff splits a long union one member per line, leading with `|`.
        pad = " " * indent
        lines = _render_type(expr.items[0], indent, first=first, last=0)
        for position, item in enumerate(expr.items[1:], start=2):
            width = last if position == len(expr.items) else 0
            rendered = _render_type(item, indent, first=indent + 2, last=width)
            lines.append(f"{pad}| {rendered[0]}")
            lines.extend(rendered[1:])
        return lines
    pad = " " * indent
    inner = " " * (indent + 4)
    joined = ", ".join(_one_line(arg) for arg in expr.args)
    if len(inner) + len(joined) <= LINE_LENGTH:
        return [f"{expr.name}[", f"{inner}{joined}", f"{pad}]"]
    lines = [f"{expr.name}["]
    for arg in expr.args:
        rendered = _render_type(arg, indent + 4, first=len(inner), last=1)
        rendered[-1] += ","
        lines.append(f"{inner}{rendered[0]}")
        lines.extend(rendered[1:])
    lines.append(f"{pad}]")
    return lines


def _literal(names: list[str]) -> Sub:
    return Sub("Literal", tuple(f'"{name}"' for name in names))


@dataclass(frozen=True, slots=True)
class Union:
    """``a | b | Sub[...]``: only a trailing subscript is ever broken."""

    items: tuple[TypeExpr, ...]


def _signature(
    name: str,
    parameters: list[tuple[str, TypeExpr | None]],
    returns: TypeExpr,
    indent: int = 4,
    body: str = " ...",
) -> list[str]:
    """Render ``def name(params) -> returns:`` the way ruff format would."""
    pad = " " * indent
    params = [
        f"{param}: {_one_line(annotation)}" if annotation is not None else param
        for param, annotation in parameters
    ]
    single = f"{pad}def {name}({', '.join(params)}) -> {_one_line(returns)}:{body}"
    if len(single) <= LINE_LENGTH:
        return [single]
    lines = [f"{pad}def {name}("]
    inner = " " * (indent + 4)
    joined = ", ".join(params)
    if len(inner) + len(joined) <= LINE_LENGTH:
        lines.append(f"{inner}{joined}")
    else:
        for param, annotation in parameters:
            if annotation is None:
                lines.append(f"{inner}{param},")
                continue
            rendered = _render_type(
                annotation, indent + 4, first=len(inner) + len(param) + 2, last=1
            )
            rendered[-1] += ","
            lines.append(f"{inner}{param}: {rendered[0]}")
            lines.extend(rendered[1:])
    tail = _render_type(returns, indent, first=len(pad) + 5, last=1 + len(body))
    lines.append(f"{pad}) -> {tail[0]}" + (f":{body}" if len(tail) == 1 else ""))
    if len(tail) > 1:
        lines.extend(tail[1:-1])
        lines.append(f"{tail[-1]}:{body}")
    return lines


def _class_header(name: str, bases: list[TypeExpr], indent: int) -> list[str]:
    """Render ``class Name(bases):`` the way ruff format would."""
    pad = " " * indent
    joined = ", ".join(_one_line(base) for base in bases)
    single = f"{pad}class {name}({joined}):"
    if len(single) <= LINE_LENGTH:
        return [single]
    inner = " " * (indent + 4)
    if len(inner) + len(joined) <= LINE_LENGTH:
        return [f"{pad}class {name}(", f"{inner}{joined}", f"{pad}):"]
    lines = [f"{pad}class {name}("]
    for base in bases:
        rendered = _render_type(base, indent + 4, first=len(inner), last=1)
        rendered[-1] += ","
        lines.append(f"{inner}{rendered[0]}")
        lines.extend(rendered[1:])
    lines.append(f"{pad}):")
    return lines


def _import_order(name: str) -> tuple[int, str]:
    """isort's default order-by-type: CONSTANTS, then Classes, then functions."""
    if name.isupper():
        return (0, name)
    if name[:1].isupper():
        return (1, name)
    return (2, name)


# --- rendering --------------------------------------------------------------


class _Renderer:
    def __init__(self, model: SchemaModel) -> None:
        self.model = model
        self.groups = model.groups
        self.group_names = [group.name for group in self.groups]
        self.lines: list[str] = []

    # type expression builders

    def row(self, **changes: str) -> Sub:
        """``DatabaseRow[...]`` with every group as its own TypeVar, or replaced."""
        args = [changes.get(name, name) for name in self.group_names]
        args.append(changes.get("NullRowT", "NullRowT"))
        return Sub("DatabaseRow", tuple(args))

    def query(self, scope: str, null: str, row: TypeExpr) -> Sub:
        return Sub("DatabaseQuery", (scope, null, row))

    def emit(self, lines: list[str]) -> None:
        self.lines.extend(lines)

    def overload(
        self,
        name: str,
        parameters: list[tuple[str, TypeExpr | None]],
        returns: TypeExpr,
        indent: int = 4,
    ) -> None:
        pad = " " * indent
        self.emit([f"{pad}@overload"])
        self.emit(_signature(name, parameters, returns, indent))
        self.emit([""])

    # sections

    def render(self, *, source: str, output: str) -> str:
        model = self.model
        module = output.rsplit("/", 1)[-1].removesuffix(".py")
        header = HEADER.format(
            source=source, output=output, module=module, schema=model.database
        )
        self.emit(
            [
                header,
                "",
                "# The typed classes overload every public method per column, so",
                "# the checks below are noise for generated code.",
                '# mypy: disable-error-code="override, overload-overlap"',
                "# pyright: reportIncompatibleMethodOverride=false",
                "# pyright: reportOverlappingOverload=false",
                "",
                "from __future__ import annotations",
                "",
            ]
        )
        self.imports()
        self.emit(
            [
                "",
                "from pysely import (",
                "    Expression,",
                "    ExpressionBuilder,",
                "    GeneratedSchema,",
                "    Pysely,",
                "    ReferenceOperator,",
                "    Row,",
                "    TypedSchemaQueryBuilder,",
                ")",
                "",
                "",
                f"# Table classes, copied from {source}.",
            ]
        )
        for statement in model.body:
            self.emit([statement, "", ""])
        self.aliases()
        self.emit(["", "if TYPE_CHECKING:"])
        self.row_class()
        self.expression_builder()
        self.query_class()
        self.client_class()
        self.emit(["else:"])
        self.runtime_classes()
        self.emit(
            [
                "",
                "",
                "# Schema class. Pass it to `Database`; its base names the client.",
                f"class {model.database}(GeneratedSchema[DatabaseClient]):",
            ]
        )
        self.emit(
            [f"    {table.attribute}: {table.class_name}" for table in model.tables]
        )
        self.emit(["", "", f"schema = {model.database}", ""])
        return "\n".join(self.lines)

    def imports(self) -> None:
        typing_names = {
            "TYPE_CHECKING",
            "Any",
            "Generic",
            "Literal",
            "LiteralString",
            "Never",
            "TypeAlias",
            "TypeVar",
            "cast",
            "overload",
        }
        standard: list[tuple[str, list[str]]] = [
            ("collections.abc", ["from collections.abc import Callable, Sequence"]),
        ]
        for item in self.model.imports:
            module = item.split()[1]
            if item.startswith("from typing import "):
                imported = item.removeprefix("from typing import ")
                typing_names.update(name.strip() for name in imported.split(","))
            else:
                standard.append((module, [item]))
        standard.append(
            (
                "typing",
                [
                    "from typing import (",
                    *[
                        f"    {name},"
                        for name in sorted(typing_names, key=_import_order)
                    ],
                    ")",
                ],
            )
        )
        for _, block in sorted(standard, key=lambda entry: entry[0]):
            self.emit(block)

    def aliases(self) -> None:
        model = self.model
        self.emit(["# Column references in scope once a table is joined."])
        for table in model.tables:
            names = model.column_literals(table)
            self.emit([f"{table.alias}: TypeAlias = Literal["])
            self.emit([f'    "{name}",' for name in names])
            self.emit(["]"])
        table_names = [table.attribute for table in model.tables]
        self.emit(
            [
                f"TableName: TypeAlias = {_one_line(_literal(table_names))}",
                "",
                "# Query state: columns in scope, tables joined nullably, row type.",
                'ColumnT = TypeVar("ColumnT", bound=str)',
                'NullT = TypeVar("NullT", bound=str)',
                'RowT = TypeVar("RowT")',
                'AliasT = TypeVar("AliasT", bound=LiteralString | Literal[""])',
                "# Row state: the selected keys of each value type, and whether an",
                "# outer join made every key nullable.",
            ]
        )
        for group in self.groups:
            self.emit([f'{group.name} = TypeVar("{group.name}", bound=str)'])
        self.emit(['NullRowT = TypeVar("NullRowT", bound=str)'])

    def row_class(self) -> None:
        generic = Sub("Generic", (*self.group_names, "NullRowT"))
        self.emit(["", *_class_header("DatabaseRow", ["Row", generic], 4)])
        self.emit(["        # After a right or full join every key may be None."])
        marked = self.row(NullRowT='Literal["*"]')
        for group in self.groups:
            if group.value == "object":
                continue
            self.overload(
                "__getitem__",
                [("self", marked), ("key", group.name)],
                _nullable(group.value)
                if not group.value.endswith("| None")
                else group.value,
                indent=8,
            )
        for group in self.groups:
            self.overload(
                "__getitem__", [("self", None), ("key", group.name)], group.value, 8
            )
        self.emit(
            [
                "        def __getitem__(self, key: str) -> object:",
                "            return super().__getitem__(key)",
                "",
            ]
        )
        for group in self.groups:
            value = group.value
            self.overload(
                "get",
                [("self", None), ("key", group.name)],
                value
                if value == "object" or value.endswith("| None")
                else _nullable(value),
                8,
            )
        self.overload("get", [("self", None), ("key", "str")], "object", 8)
        self.emit(
            [
                "        def get(self, key: str, default: object = None) -> object:",
                "            return super().get(key, default)",
                "",
            ]
        )

    def _where_shapes(
        self, table: Table, *, exact: bool
    ) -> list[tuple[list[str], str, TypeExpr]]:
        """(column names, operator literal, value type) for every where overload."""
        model = self.model
        shapes: list[tuple[list[str], str, TypeExpr]] = []
        by_value: dict[str, list[str]] = {}
        all_names: list[str] = []
        for column in table.columns:
            names = [column.name] if exact else model.references(table, column.name)
            if exact and not model.shared(column.name):
                continue
            by_value.setdefault(column.value, []).extend(names)
            all_names.extend(names)
        for value, names in by_value.items():
            shapes.append((names, COMPARE, value))
            shapes.append(
                (
                    names,
                    COLLECTION,
                    Union((Sub("list", (value,)), Sub("tuple", (value, "...")))),
                )
            )
            if _string_like(value):
                shapes.append((names, PATTERN, "str"))
        if all_names:
            shapes.append((all_names, NULL_TEST, "None"))
        return shapes

    def expression_builder(self) -> None:
        model = self.model
        self.emit(
            [
                "    class DatabaseExpressionBuilder(ExpressionBuilder[ColumnT]):",
                "        # Callback predicates get the same scope and value checks as",
                "        # a flat where() call.",
            ]
        )
        for table in model.tables:
            for exact in (True, False):
                scope = table.alias if exact else f"ColumnT | {table.alias}"
                for names, operator, value in self._where_shapes(table, exact=exact):
                    self.overload(
                        "__call__",
                        [
                            ("self", Sub("DatabaseExpressionBuilder", (scope,))),
                            ("column", _literal(names)),
                            ("operator", operator),
                            ("value", value),
                        ],
                        "Expression[bool]",
                        8,
                    )
        self.emit(
            _signature(
                "__call__",
                [
                    ("self", None),
                    ("column", "Any"),
                    ("operator", "Any"),
                    ("value", "Any"),
                ],
                "Expression[bool]",
                8,
                body="",
            )
        )
        self.emit(["            return super().__call__(column, operator, value)", ""])
        for table in model.tables:
            bare = [c.name for c in table.columns if model.shared(c.name)]
            if not bare:
                continue
            self.overload(
                "ref",
                [
                    ("self", Sub("DatabaseExpressionBuilder", (table.alias,))),
                    ("left", Union((table.alias, _literal(bare)))),
                    ("operator", "ReferenceOperator"),
                    ("right", Union((table.alias, _literal(bare)))),
                ],
                "Expression[bool]",
                8,
            )
        self.overload(
            "ref",
            [
                ("self", None),
                ("left", "ColumnT"),
                ("operator", "ReferenceOperator"),
                ("right", "ColumnT"),
            ],
            "Expression[bool]",
            8,
        )
        self.emit(
            [
                "        def ref(",
                "            self, left: Any, operator: ReferenceOperator, right: Any",
                "        ) -> Expression[bool]:",
                "            return super().ref(left, operator, right)",
                "",
            ]
        )

    def query_class(self) -> None:
        model = self.model
        self.emit(
            [
                "    class DatabaseQuery(",
                f'        TypedSchemaQueryBuilder["{model.database}", ColumnT, RowT],',
                "        Generic[ColumnT, NullT, RowT],",
                "    ):",
                "        # select: one overload per column. The nullable form comes",
                "        # first and only matches once the table is outer-joined.",
            ]
        )
        row = self.row()
        for table in model.tables:
            nullable_scope = f'NullT | Literal["{table.attribute}"]'
            for column in table.columns:
                names = model.references(table, column.name)
                key = f'Literal["{column.name}"]'
                plain = model.group(column.value, column.nullable)
                optional = model.group(column.value, True)
                scope = f"ColumnT | {table.alias}"
                self.overload(
                    "select",
                    [
                        ("self", self.query(scope, nullable_scope, row)),
                        ("selections", _literal(names)),
                    ],
                    self.query(
                        scope,
                        nullable_scope,
                        self.row(**{optional.name: f"{optional.name} | {key}"}),
                    ),
                    8,
                )
                self.overload(
                    "select",
                    [
                        ("self", self.query(scope, "NullT", row)),
                        ("selections", _literal(names)),
                    ],
                    self.query(
                        scope,
                        "NullT",
                        self.row(**{plain.name: f"{plain.name} | {key}"}),
                    ),
                    8,
                )
                if model.shared(column.name):
                    self.overload(
                        "select",
                        [
                            ("self", self.query(table.alias, "Never", row)),
                            ("selections", _literal([column.name])),
                        ],
                        self.query(
                            table.alias,
                            "Never",
                            self.row(**{plain.name: f"{plain.name} | {key}"}),
                        ),
                        8,
                    )
        object_group = self.groups[-1].name
        self.overload(
            "select",
            [
                ("self", self.query("ColumnT", "NullT", row)),
                ("selections", "ColumnT | Sequence[ColumnT]"),
            ],
            self.query("ColumnT", "NullT", self.row(**{object_group: "str"})),
            8,
        )
        self.emit(
            [
                "        def select(self, selections: Any) -> Any:",
                "            return super().select(selections)",
                "",
                "        # select_as: grouped by value type; the alias becomes a key.",
            ]
        )
        for table in model.tables:
            nullable_scope = f'NullT | Literal["{table.attribute}"]'
            scope = f"ColumnT | {table.alias}"
            by_value: dict[tuple[str, bool], list[str]] = {}
            bare: dict[tuple[str, bool], list[str]] = {}
            for column in table.columns:
                by_value.setdefault((column.value, column.nullable), []).extend(
                    model.references(table, column.name)
                )
                if model.shared(column.name):
                    bare.setdefault((column.value, column.nullable), []).append(
                        column.name
                    )
            for (value, nullable), names in by_value.items():
                plain = model.group(value, nullable)
                optional = model.group(value, True)
                self.overload(
                    "select_as",
                    [
                        ("self", self.query(scope, nullable_scope, row)),
                        ("source", _literal(names)),
                        ("alias", "AliasT"),
                    ],
                    self.query(
                        scope,
                        nullable_scope,
                        self.row(**{optional.name: f"{optional.name} | AliasT"}),
                    ),
                    8,
                )
                self.overload(
                    "select_as",
                    [
                        ("self", self.query(scope, "NullT", row)),
                        ("source", _literal(names)),
                        ("alias", "AliasT"),
                    ],
                    self.query(
                        scope,
                        "NullT",
                        self.row(**{plain.name: f"{plain.name} | AliasT"}),
                    ),
                    8,
                )
            for (value, nullable), names in bare.items():
                plain = model.group(value, nullable)
                self.overload(
                    "select_as",
                    [
                        ("self", self.query(table.alias, "Never", row)),
                        ("source", _literal(names)),
                        ("alias", "AliasT"),
                    ],
                    self.query(
                        table.alias,
                        "Never",
                        self.row(**{plain.name: f"{plain.name} | AliasT"}),
                    ),
                    8,
                )
        self.overload(
            "select_as",
            [
                ("self", self.query("ColumnT", "NullT", row)),
                ("source", "ColumnT"),
                ("alias", "str"),
            ],
            self.query("ColumnT", "NullT", self.row(**{object_group: "str"})),
            8,
        )
        self.emit(
            [
                "        def select_as(self, source: Any, alias: str) -> Any:",
                "            return self._select_as(source, alias)",
                "",
                "        # where: operator families take different value shapes.",
            ]
        )
        for table in model.tables:
            for exact in (True, False):
                scope = table.alias if exact else f"ColumnT | {table.alias}"
                null = "Never" if exact else "NullT"
                for names, operator, shape in self._where_shapes(table, exact=exact):
                    self.overload(
                        "where",
                        [
                            ("self", self.query(scope, null, "RowT")),
                            ("column", _literal(names)),
                            ("operator", operator),
                            ("value", shape),
                        ],
                        self.query(scope, null, "RowT"),
                        8,
                    )
        self.overload(
            "where",
            [
                ("self", None),
                (
                    "column",
                    "Callable[[DatabaseExpressionBuilder[ColumnT]], Expression[bool]]",
                ),
            ],
            self.query("ColumnT", "NullT", "RowT"),
            8,
        )
        self.emit(
            _signature(
                "where",
                [
                    ("self", None),
                    ("column", "Any"),
                    ("operator: Any = None", None),
                    ("value: Any = None", None),
                ],
                "Any",
                8,
                body="",
            )
        )
        self.emit(
            [
                "            if isinstance(column, str):",
                "                name = cast(Any, column)",
                "                return super().where(name, operator, value)",
                "            return super().where(column)",
                "",
            ]
        )
        for table in model.tables:
            shared = [c.name for c in table.columns if model.shared(c.name)]
            if not shared:
                continue
            self.overload(
                "where_ref",
                [
                    ("self", self.query(table.alias, "Never", "RowT")),
                    ("left", Union((table.alias, _literal(shared)))),
                    ("operator", "ReferenceOperator"),
                    ("right", Union((table.alias, _literal(shared)))),
                ],
                self.query(table.alias, "Never", "RowT"),
                8,
            )
        self.overload(
            "where_ref",
            [
                ("self", None),
                ("left", "ColumnT"),
                ("operator", "ReferenceOperator"),
                ("right", "ColumnT"),
            ],
            self.query("ColumnT", "NullT", "RowT"),
            8,
        )
        self.emit(
            [
                "        def where_ref(self, left: Any, operator: Any, right: Any)"
                " -> Any:",
                "            return super().where_ref(left, operator, right)",
                "",
                "        # joins: the ON columns may use the prior scope and the new",
                "        # table. Outer joins record which side may be missing.",
            ]
        )
        for kind in ("inner", "left", "right", "full"):
            for table in model.tables:
                scope = f"ColumnT | {table.alias}"
                marked = f'NullT | Literal["{table.attribute}"]'
                if kind == "inner":
                    returns = self.query(scope, "NullT", "RowT")
                elif kind == "left":
                    returns = self.query(scope, marked, "RowT")
                elif kind == "right":
                    returns = self.query(
                        scope, "NullT", self.row(NullRowT='Literal["*"]')
                    )
                else:
                    returns = self.query(
                        scope, marked, self.row(NullRowT='Literal["*"]')
                    )
                self_type: TypeExpr | None = (
                    self.query("ColumnT", "NullT", row)
                    if kind in {"right", "full"}
                    else None
                )
                self.overload(
                    f"{kind}_join",
                    [
                        ("self", self_type),
                        ("table", f'Literal["{table.attribute}"]'),
                        ("left", scope),
                        ("right", scope),
                    ],
                    returns,
                    8,
                )
            self.emit(
                [
                    f"        def {kind}_join(self, table: Any, left: Any, right: Any)"
                    " -> Any:",
                    f'            return self._join("{kind}", table, left, right)',
                    "",
                ]
            )

    def client_class(self) -> None:
        model = self.model
        self.emit(
            [
                "    # Typed client. `Database(schema=...)` builds and returns this.",
                f'    class DatabaseClient(Pysely["{model.database}"]):',
            ]
        )
        for table in model.tables:
            self.overload(
                "select_from",
                [("self", None), ("table", f'Literal["{table.attribute}"]')],
                self.query(
                    table.alias,
                    "Never",
                    self.row(
                        **dict.fromkeys(self.group_names, "Never"), NullRowT="Never"
                    ),
                ),
                8,
            )
        self.emit(
            [
                "        def select_from(self, table: str) -> Any:",
                "            query = super().select_from(table)",
                "            builder = DatabaseExpressionBuilder",
                "            return DatabaseQuery(query.with_types(DatabaseRow, "
                "builder))",
                "",
            ]
        )

    def runtime_classes(self) -> None:
        self.emit(
            [
                "    # Runtime twins of the typed classes: no overloads, so importing",
                "    # this module costs the same for any schema size.",
                "    class DatabaseRow(Row):",
                "        pass",
                "",
                "    class DatabaseExpressionBuilder(ExpressionBuilder):",
                "        pass",
                "",
                "    class DatabaseQuery(TypedSchemaQueryBuilder):",
                "        def select_as(self, source, alias):",
                "            return self._select_as(source, alias)",
                "",
            ]
        )
        for kind in ("inner", "left", "right", "full"):
            self.emit(
                [
                    f"        def {kind}_join(self, table, left, right):",
                    f'            return self._join("{kind}", table, left, right)',
                    "",
                ]
            )
        self.emit(
            [
                "    class DatabaseClient(Pysely):",
                "        def select_from(self, table):",
                "            query = super().select_from(table)",
                "            builder = DatabaseExpressionBuilder",
                "            return DatabaseQuery(query.with_types(DatabaseRow, "
                "builder))",
            ]
        )


def render(
    model: SchemaModel, *, source: str = "tables.py", output: str = "schema.py"
) -> str:
    return _Renderer(model).render(source=source, output=output)


def generate(
    source: str, *, source_name: str = "tables.py", output: str = "schema.py"
) -> str:
    """Turn table-class source into typed schema-module source."""
    return render(
        parse_schema(source, filename=source_name), source=source_name, output=output
    )
