"""Generate a typed query interface from annotated schema classes.

Pyright has no plugin interface, so the only way a standard editor can check
string column names is for the literal types to exist in real annotations.
This module writes those annotations from the schema classes the user already
maintains.

The generator parses the schema module with :mod:`ast`. It never imports or
executes it, and it never connects to a database.

The output is one self-contained module. It carries a copy of the schema
classes alongside the typed interface, so an application imports the generated
module alone and nothing depends on where the schema module lives.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass

_SINGLE_QUOTED = re.compile(r"'([^'\"\\]*)'")

LINE_LENGTH = 88

# Names the generated module defines itself, so the schema cannot use them.
RESERVED_NAMES = frozenset({"DatabaseClient", "DatabaseQuery"})

HEADER = '''"""Generated by `pysely codegen` from {source}. Do not edit.

This module is self-contained: it carries the schema classes and the typed
client built from them. Pass the schema class to `Pysely.create`:

    from pysely import Pysely
    from {module} import {schema}

    db = Pysely.create(schema={schema}, dialect=dialect)

Regenerate with:

    pysely codegen {source} \\
        --output {output}
"""'''


class SchemaError(ValueError):
    """Raised when a schema module cannot be turned into a typed interface."""


@dataclass(frozen=True, slots=True)
class Column:
    name: str
    annotation: str


@dataclass(frozen=True, slots=True)
class Table:
    attribute: str
    class_name: str
    alias: str
    columns: tuple[Column, ...]


@dataclass(frozen=True, slots=True)
class SchemaModel:
    database: str
    tables: tuple[Table, ...]
    imports: tuple[str, ...]
    body: tuple[str, ...]
    """Every top-level statement that is not an import, re-rendered as source."""

    def references(self, table: Table, column: str) -> list[str]:
        """Names that resolve to a column: qualified always, bare when unique."""
        owners = sum(
            any(item.name == column for item in other.columns) for other in self.tables
        )
        names = [f"{table.attribute}.{column}"]
        if owners == 1:
            names.append(column)
        return names

    def column_literals(self, table: Table) -> list[str]:
        """Every name in scope for a table, qualified names first."""
        references = [self.references(table, column.name) for column in table.columns]
        return [names[0] for names in references] + [
            names[1] for names in references if len(names) > 1
        ]


def _annotation(node: ast.expr) -> str:
    """Unparse an annotation using the double quotes ruff format expects."""
    return _SINGLE_QUOTED.sub(r'"\1"', ast.unparse(node))


def _import_order(name: str) -> tuple[int, str]:
    """isort's default order-by-type: CONSTANTS, then Classes, then functions."""
    if name.isupper():
        return (0, name)
    if name[:1].isupper():
        return (1, name)
    return (2, name)


def _literal(names: list[str]) -> str:
    return f"Literal[{', '.join(chr(34) + name + chr(34) for name in names)}]"


def _block(prefix: str, arguments: list[str], suffix: str, indent: int) -> list[str]:
    """Render ``prefix[a, b, c]suffix`` the way ruff format would."""
    pad = " " * indent
    single = f"{pad}{prefix}[{', '.join(arguments)}]{suffix}"
    if len(single) <= LINE_LENGTH:
        return [single]
    inner = " " * (indent + 4)
    joined = ", ".join(arguments)
    if len(inner) + len(joined) <= LINE_LENGTH:
        return [f"{pad}{prefix}[", f"{inner}{joined}", f"{pad}]{suffix}"]
    body = [f"{inner}{item}," for item in arguments]
    return [f"{pad}{prefix}[", *body, f"{pad}]{suffix}"]


def _signature(
    name: str, parameters: list[str], returns: list[str], indent: int = 4
) -> list[str]:
    """Render an overload the way ruff format would."""
    pad = " " * indent
    single = f"{pad}def {name}({', '.join(parameters)}) -> {returns[0].strip()}"
    if len(returns) == 1 and len(single) <= LINE_LENGTH:
        return [single]
    first, *rest = returns
    return [
        f"{pad}def {name}(",
        *[f"{pad}    {parameter}," for parameter in parameters],
        f"{pad}) -> {first.strip()}",
        *rest,
    ]


def parse_schema(source: str, *, filename: str = "schema.py") -> SchemaModel:
    """Read annotated classes out of a schema module."""
    tree = ast.parse(source, filename=filename)
    imports = tuple(
        ast.unparse(node)
        for node in tree.body
        if isinstance(node, ast.Import | ast.ImportFrom)
        and not (isinstance(node, ast.ImportFrom) and node.module == "__future__")
    )
    classes: dict[str, dict[str, str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        fields: dict[str, str] = {}
        for item in node.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                fields[item.target.id] = _annotation(item.annotation)
        classes[node.name] = fields

    database = next(
        (
            name
            for name, fields in classes.items()
            if fields and all(value in classes for value in fields.values())
        ),
        None,
    )
    if database is None:
        raise SchemaError(
            "No database class found: expected a class whose annotations are all "
            "other classes in the same module"
        )
    taken = RESERVED_NAMES & set(classes)
    if taken:
        names = ", ".join(sorted(taken))
        raise SchemaError(
            f"Schema class name reserved by the generated module: {names}. "
            "Rename it (for example DatabaseSchema)."
        )
    tables: list[Table] = []
    for attribute, class_name in classes[database].items():
        columns = classes[class_name]
        if not columns:
            raise SchemaError(f"Table class {class_name} has no annotated columns")
        tables.append(
            Table(
                attribute=attribute,
                class_name=class_name,
                alias=f"{class_name.removesuffix('Table')}Columns",
                columns=tuple(
                    Column(name, annotation) for name, annotation in columns.items()
                ),
            )
        )
    if not tables:
        raise SchemaError(f"Database class {database} declares no tables")
    body = tuple(
        _SINGLE_QUOTED.sub(r'"\1"', ast.unparse(node))
        for node in tree.body
        if not isinstance(node, ast.Import | ast.ImportFrom)
        and not (isinstance(node, ast.ClassDef) and node.name == database)
    )
    return SchemaModel(
        database=database, tables=tuple(tables), imports=imports, body=body
    )


def render(
    model: SchemaModel, *, source: str = "schema.py", output: str = "db.py"
) -> str:
    module = output.rsplit("/", 1)[-1].removesuffix(".py")
    header = HEADER.format(
        source=source, output=output, module=module, schema=model.database
    )
    lines: list[str] = [header, ""]
    lines.append("from __future__ import annotations")
    lines.append("")
    typing_names = {
        "Any",
        "Literal",
        "LiteralString",
        "Never",
        "TypeAlias",
        "TypeVar",
        "cast",
        "overload",
    }
    standard: list[tuple[str, list[str]]] = [
        ("collections.abc", ["from collections.abc import Callable"]),
    ]
    for item in model.imports:
        module = item.split()[1]
        if item.startswith("from typing import "):
            imported = item.removeprefix("from typing import ")
            typing_names.update(name.strip() for name in imported.split(","))
        else:
            standard.append((module, [item]))
    standard.append(
        (
            "typing",
            [
                "from typing import (",
                *[f"    {name}," for name in sorted(typing_names, key=_import_order)],
                ")",
            ],
        )
    )
    for _, block in sorted(standard, key=lambda entry: entry[0]):
        lines += block
    lines += [
        "",
        "from pysely import (",
        "    Expression,",
        "    ExpressionBuilder,",
        "    GeneratedSchema,",
        "    Pysely,",
        "    SchemaComparisonOperator,",
        "    TypedSchemaQueryBuilder,",
        ")",
        "",
        "",
        f"# Table classes, copied from {source}.",
    ]
    for statement in model.body:
        lines += [statement, "", ""]

    lines.append("# Typed query builder, one overload per column.")
    for table in model.tables:
        names = model.column_literals(table)
        lines.append(f"{table.alias}: TypeAlias = Literal[")
        lines += [f'    "{name}",' for name in names]
        lines.append("]")
    table_names = [table.attribute for table in model.tables]
    aliases = [table.alias for table in model.tables]
    lines.append(f"TableName: TypeAlias = {_literal(table_names)}")
    lines.append(f"AllColumns: TypeAlias = {' | '.join(aliases)}")
    lines += [
        'ColumnT = TypeVar("ColumnT", bound=str)',
        'ResultKeyT = TypeVar("ResultKeyT", bound=str)',
        'ResultValueT = TypeVar("ResultValueT")',
        'AliasT = TypeVar("AliasT", bound=LiteralString | Literal[""])',
        "",
        "",
        "class DatabaseQuery(",
        f'    TypedSchemaQueryBuilder["{model.database}", ColumnT, '
        "dict[ResultKeyT, ResultValueT]]",
        "):",
    ]

    for table in model.tables:
        for column in table.columns:
            names = model.references(table, column.name)
            lines.append("    @overload")
            lines += _signature(
                "select",
                [
                    f"self: DatabaseQuery[ColumnT | {table.alias}, ResultKeyT, "
                    "ResultValueT]",
                    f"selections: {_literal(names)}",
                ],
                _block(
                    "DatabaseQuery",
                    [
                        f"ColumnT | {table.alias}",
                        f'ResultKeyT | Literal["{column.name}"]',
                        f"ResultValueT | {column.annotation}",
                    ],
                    ": ...",
                    4,
                ),
            )
            lines.append("")
    lines += [
        "    @overload",
        "    def select(",
        "        self, selections: ColumnT | list[ColumnT] | tuple[ColumnT, ...]",
        "    ) -> DatabaseQuery[ColumnT, str, object]: ...",
        "",
        "    def select(",
        "        self, selections: str | list[Any] | tuple[str, ...]",
        "    ) -> DatabaseQuery[Any, Any, Any]:",
        "        return cast(DatabaseQuery[Any, Any, Any], "
        "super().select(cast(Any, selections)))",
        "",
    ]

    grouped: dict[str, list[str]] = {}
    for table in model.tables:
        for column in table.columns:
            grouped.setdefault(column.annotation, []).extend(
                model.references(table, column.name)
            )
    for annotation, names in grouped.items():
        lines.append("    @overload")
        lines += _signature(
            "select_as",
            ["self", f"source: {_literal(names)}", "alias: AliasT"],
            _block(
                "DatabaseQuery",
                ["ColumnT", "ResultKeyT | AliasT", f"ResultValueT | {annotation}"],
                ": ...",
                4,
            ),
        )
        lines.append("")
    lines += [
        "    @overload",
        "    def select_as(",
        "        self, source: ColumnT, alias: str",
        "    ) -> DatabaseQuery[ColumnT, str, object]: ...",
        "",
        "    def select_as(self, source: str, alias: str) -> "
        "DatabaseQuery[Any, Any, Any]:",
        "        return cast(",
        "            DatabaseQuery[Any, Any, Any],",
        "            self._select_as(cast(Any, source), alias),",
        "        )",
        "",
    ]

    first = True
    for table in model.tables:
        per_type: dict[str, list[str]] = {}
        for column in table.columns:
            per_type.setdefault(column.annotation, []).extend(
                model.references(table, column.name)
            )
        for annotation, names in per_type.items():
            lines.append(
                "    @overload  # type: ignore[override]" if first else "    @overload"
            )
            first = False
            lines += _signature(
                "where",
                [
                    f"self: DatabaseQuery[ColumnT | {table.alias}, ResultKeyT, "
                    "ResultValueT]",
                    f"column: {_literal(names)}",
                    "operator: SchemaComparisonOperator",
                    f"value: {annotation}",
                ],
                _block(
                    "DatabaseQuery",
                    [f"ColumnT | {table.alias}", "ResultKeyT", "ResultValueT"],
                    ": ...",
                    4,
                ),
            )
            lines.append("")
    lines += [
        "    @overload",
        "    def where(",
        "        self,",
        "        column: Callable[[ExpressionBuilder[ColumnT]], Expression[bool]],",
        "    ) -> DatabaseQuery[ColumnT, ResultKeyT, ResultValueT]: ...",
        "",
        "    def where(  # pyright: ignore[reportIncompatibleMethodOverride]",
        "        self,",
        "        column: str | "
        "Callable[[ExpressionBuilder[ColumnT]], Expression[bool]],",
        "        operator: SchemaComparisonOperator | None = None,",
        "        value: object = None,",
        "    ) -> DatabaseQuery[Any, Any, Any]:",
        "        if callable(column):",
        "            return cast(DatabaseQuery[Any, Any, Any], super().where(column))",
        "        if operator is None:",
        '            raise TypeError("where() requires an operator and value")',
        "        return cast(",
        "            DatabaseQuery[Any, Any, Any],",
        "            super().where(cast(Any, column), operator, value),",
        "        )",
        "",
    ]

    for table in model.tables:
        lines.append("    @overload")
        lines += _signature(
            "inner_join",
            [
                "self",
                f'table: Literal["{table.attribute}"]',
                f"left: ColumnT | {table.alias}",
                f"right: ColumnT | {table.alias}",
            ],
            _block(
                "DatabaseQuery",
                [f"ColumnT | {table.alias}", "ResultKeyT", "ResultValueT"],
                ": ...",
                4,
            ),
        )
        lines.append("")
    lines += [
        "    @overload",
        "    def inner_join(",
        "        self,",
        "        table: TableName,",
        "        left: ColumnT | AllColumns,",
        "        right: ColumnT | AllColumns,",
        "    ) -> DatabaseQuery[Any, ResultKeyT, ResultValueT]: ...",
        "",
        "    def inner_join(",
        "        self, table: str, left: str, right: str",
        "    ) -> DatabaseQuery[Any, Any, Any]:",
        "        return cast(DatabaseQuery[Any, Any, Any], "
        "self._inner_join(table, left, right))",
        "",
        "",
        "# Typed client. `Pysely.create(schema=...)` builds and returns this.",
        f'class DatabaseClient(Pysely["{model.database}"]):',
    ]
    first = True
    for table in model.tables:
        lines += [
            "    @overload  # type: ignore[override]" if first else "    @overload",
            "    def select_from(",
            f'        self, table: Literal["{table.attribute}"]',
            f"    ) -> DatabaseQuery[{table.alias}, Never, Never]: ...",
            "",
        ]
        first = False
    lines += [
        "    @overload",
        "    def select_from(self, table: TableName) -> "
        "DatabaseQuery[Any, Never, Never]: ...",
        "",
        "    def select_from(  # pyright: ignore[reportIncompatibleMethodOverride]",
        "        self, table: str",
        "    ) -> DatabaseQuery[Any, Never, Never]:",
        "        return cast(",
        "            DatabaseQuery[Any, Never, Never],",
        "            DatabaseQuery(super().select_from(table)),",
        "        )",
        "",
        "",
        "# Schema class. Pass it to `Pysely.create`; its base names the client.",
        f"class {model.database}(GeneratedSchema[DatabaseClient]):",
    ]
    lines += [f"    {table.attribute}: {table.class_name}" for table in model.tables]
    return "\n".join(lines) + "\n"


def generate(
    source: str, *, source_name: str = "schema.py", output: str = "db.py"
) -> str:
    """Turn schema-module source into typed interface source."""
    return render(
        parse_schema(source, filename=source_name), source=source_name, output=output
    )
