"""Typed result rows. Generated by scripts/generate_row.py; do not edit."""

# The per-depth overloads narrow Mapping's key type on purpose.
# pyright: reportIncompatibleMethodOverride=false, reportOverlappingOverload=false
# mypy: disable-error-code="override, overload-overlap"

from __future__ import annotations

from collections.abc import Iterator, Mapping
from typing import Any, Generic, Literal, TypeVar, overload

K = TypeVar("K", bound=str)
V = TypeVar("V")
R = TypeVar("R")
FieldsT = TypeVar("FieldsT")
StarT = TypeVar("StarT", bound=str)


class Nil:
    """The fields of a query that has selected nothing yet."""


class Cons(Generic[K, V, R]):
    """One selected field (key, value type) in front of the fields before it."""


class Row(Mapping[str, object], Generic[FieldsT, StarT]):
    """An immutable result row addressed by output column name.

    ``FieldsT`` lists the selected fields newest first; ``StarT`` is
    ``Literal["*"]`` once a right or full join has made every key nullable.
    Lookups are typed for the first 16 fields; beyond that a key reads as
    ``object``. The overloads reject unknown keys, which also means checkers do
    not see the row as a plain ``Mapping[str, ...]`` for ``dict(row)`` or
    ``**row``; use ``row.to_dict()``.
    """

    __slots__ = ("_data",)

    def __init__(self, data: Mapping[str, object]) -> None:
        self._data: dict[str, object] = dict(data)

    @overload
    def __getitem__(self: Row[Cons[K, V, Any], Literal["*"]], key: K) -> V | None: ...

    @overload
    def __getitem__(self: Row[Cons[K, V, Any], StarT], key: K) -> V: ...

    @overload
    def __getitem__(
        self: Row[Cons[Any, Any, Cons[K, V, Any]], Literal["*"]], key: K
    ) -> V | None: ...

    @overload
    def __getitem__(self: Row[Cons[Any, Any, Cons[K, V, Any]], StarT], key: K) -> V: ...

    @overload
    def __getitem__(
        self: Row[Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]], Literal["*"]], key: K
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]], StarT], key: K
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]], StarT
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[Any, Any, Cons[K, V, Any]],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[Any, Any, Cons[K, V, Any]],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[Any, Any, Cons[K, V, Any]],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[Any, Any, Cons[K, V, Any]],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[Any, Any, Cons[K, V, Any]],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[Any, Any, Cons[K, V, Any]],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[K, V, Any],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[K, V, Any],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[K, V, Any],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[K, V, Any],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[
                                                                        Any,
                                                                        Any,
                                                                        Cons[K, V, Any],
                                                                    ],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[
                                                                        Any,
                                                                        Any,
                                                                        Cons[K, V, Any],
                                                                    ],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V: ...

    # More than 16 fields: later keys are looked up at runtime only.
    @overload
    def __getitem__(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[
                                                                        Any,
                                                                        Any,
                                                                        Cons[
                                                                            Any,
                                                                            Any,
                                                                            Cons[
                                                                                Any,
                                                                                Any,
                                                                                Any,
                                                                            ],
                                                                        ],
                                                                    ],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: str,
    ) -> object: ...

    def __getitem__(self, key: Any) -> Any:
        return self._data[key]

    @overload
    def get(self: Row[Cons[K, V, Any], Literal["*"]], key: K) -> V | None: ...

    @overload
    def get(self: Row[Cons[K, V, Any], StarT], key: K) -> V | None: ...

    @overload
    def get(
        self: Row[Cons[Any, Any, Cons[K, V, Any]], Literal["*"]], key: K
    ) -> V | None: ...

    @overload
    def get(self: Row[Cons[Any, Any, Cons[K, V, Any]], StarT], key: K) -> V | None: ...

    @overload
    def get(
        self: Row[Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]], Literal["*"]], key: K
    ) -> V | None: ...

    @overload
    def get(
        self: Row[Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]], StarT], key: K
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]], StarT
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[Any, Any, Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]]],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[Any, Any, Cons[Any, Any, Cons[K, V, Any]]],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[Any, Any, Cons[K, V, Any]],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[Any, Any, Cons[K, V, Any]],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[Any, Any, Cons[K, V, Any]],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[Any, Any, Cons[K, V, Any]],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[Any, Any, Cons[K, V, Any]],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[Any, Any, Cons[K, V, Any]],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[K, V, Any],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[K, V, Any],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[K, V, Any],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[K, V, Any],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[
                                                                        Any,
                                                                        Any,
                                                                        Cons[K, V, Any],
                                                                    ],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            Literal["*"],
        ],
        key: K,
    ) -> V | None: ...

    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[
                                                                        Any,
                                                                        Any,
                                                                        Cons[K, V, Any],
                                                                    ],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: K,
    ) -> V | None: ...

    # More than 16 fields: later keys are looked up at runtime only.
    @overload
    def get(
        self: Row[
            Cons[
                Any,
                Any,
                Cons[
                    Any,
                    Any,
                    Cons[
                        Any,
                        Any,
                        Cons[
                            Any,
                            Any,
                            Cons[
                                Any,
                                Any,
                                Cons[
                                    Any,
                                    Any,
                                    Cons[
                                        Any,
                                        Any,
                                        Cons[
                                            Any,
                                            Any,
                                            Cons[
                                                Any,
                                                Any,
                                                Cons[
                                                    Any,
                                                    Any,
                                                    Cons[
                                                        Any,
                                                        Any,
                                                        Cons[
                                                            Any,
                                                            Any,
                                                            Cons[
                                                                Any,
                                                                Any,
                                                                Cons[
                                                                    Any,
                                                                    Any,
                                                                    Cons[
                                                                        Any,
                                                                        Any,
                                                                        Cons[
                                                                            Any,
                                                                            Any,
                                                                            Cons[
                                                                                Any,
                                                                                Any,
                                                                                Any,
                                                                            ],
                                                                        ],
                                                                    ],
                                                                ],
                                                            ],
                                                        ],
                                                    ],
                                                ],
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ],
        key: str,
    ) -> object: ...

    @overload
    def get(self, key: str, default: object = None) -> object: ...

    def get(self, key: Any, default: Any = None) -> Any:
        return self._data.get(key, default)

    def __iter__(self) -> Iterator[str]:
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)

    def to_dict(self) -> dict[str, object]:
        return dict(self._data)

    def __repr__(self) -> str:
        return f"{type(self).__name__}({self._data!r})"
