"""Generated by `pysely codegen` from docs/assets/examples/schema.py. Do not edit.

This module is self-contained: it carries the schema classes and the typed
client built from them. Pass the schema class to `Pysely.create`:

    from pysely import Pysely
    from database import DatabaseSchema

    db = Pysely.create(schema=DatabaseSchema, dialect=dialect)

Regenerate with:

    pysely codegen docs/assets/examples/schema.py \
        --output docs/assets/examples/database.py
"""

from __future__ import annotations

from collections.abc import Callable
from typing import (
    Any,
    Literal,
    LiteralString,
    Never,
    TypeAlias,
    TypeVar,
    cast,
    overload,
)

from pysely import (
    Expression,
    ExpressionBuilder,
    GeneratedSchema,
    Pysely,
    SchemaComparisonOperator,
    TypedSchemaQueryBuilder,
)


# Table classes, copied from docs/assets/examples/schema.py.
class PersonTable:
    id: int
    first_name: str
    last_name: str | None
    status: Literal["active", "inactive"]


class PetTable:
    id: int
    owner_id: int
    name: str
    species: Literal["cat", "dog", "hamster"]


# Typed query builder, one overload per column.
PersonColumns: TypeAlias = Literal[
    "person.id",
    "person.first_name",
    "person.last_name",
    "person.status",
    "first_name",
    "last_name",
    "status",
]
PetColumns: TypeAlias = Literal[
    "pet.id",
    "pet.owner_id",
    "pet.name",
    "pet.species",
    "owner_id",
    "name",
    "species",
]
TableName: TypeAlias = Literal["person", "pet"]
AllColumns: TypeAlias = PersonColumns | PetColumns
ColumnT = TypeVar("ColumnT", bound=str)
ResultKeyT = TypeVar("ResultKeyT", bound=str)
ResultValueT = TypeVar("ResultValueT")
AliasT = TypeVar("AliasT", bound=LiteralString | Literal[""])


class DatabaseQuery(
    TypedSchemaQueryBuilder["DatabaseSchema", ColumnT, dict[ResultKeyT, ResultValueT]]
):
    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.id"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns, ResultKeyT | Literal["id"], ResultValueT | int
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.first_name", "first_name"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns, ResultKeyT | Literal["first_name"], ResultValueT | str
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.last_name", "last_name"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns,
        ResultKeyT | Literal["last_name"],
        ResultValueT | str | None,
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.status", "status"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns,
        ResultKeyT | Literal["status"],
        ResultValueT | Literal["active", "inactive"],
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.id"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns, ResultKeyT | Literal["id"], ResultValueT | int
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.owner_id", "owner_id"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns, ResultKeyT | Literal["owner_id"], ResultValueT | int
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.name", "name"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns, ResultKeyT | Literal["name"], ResultValueT | str
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.species", "species"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns,
        ResultKeyT | Literal["species"],
        ResultValueT | Literal["cat", "dog", "hamster"],
    ]: ...

    @overload
    def select(
        self, selections: ColumnT | list[ColumnT] | tuple[ColumnT, ...]
    ) -> DatabaseQuery[ColumnT, str, object]: ...

    def select(
        self, selections: str | list[Any] | tuple[str, ...]
    ) -> DatabaseQuery[Any, Any, Any]:
        return cast(DatabaseQuery[Any, Any, Any], super().select(cast(Any, selections)))

    @overload
    def select_as(
        self,
        source: Literal["person.id", "pet.id", "pet.owner_id", "owner_id"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | int]: ...

    @overload
    def select_as(
        self,
        source: Literal["person.first_name", "first_name", "pet.name", "name"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | str]: ...

    @overload
    def select_as(
        self,
        source: Literal["person.last_name", "last_name"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | str | None]: ...

    @overload
    def select_as(
        self,
        source: Literal["person.status", "status"],
        alias: AliasT,
    ) -> DatabaseQuery[
        ColumnT, ResultKeyT | AliasT, ResultValueT | Literal["active", "inactive"]
    ]: ...

    @overload
    def select_as(
        self,
        source: Literal["pet.species", "species"],
        alias: AliasT,
    ) -> DatabaseQuery[
        ColumnT, ResultKeyT | AliasT, ResultValueT | Literal["cat", "dog", "hamster"]
    ]: ...

    @overload
    def select_as(
        self, source: ColumnT, alias: str
    ) -> DatabaseQuery[ColumnT, str, object]: ...

    def select_as(self, source: str, alias: str) -> DatabaseQuery[Any, Any, Any]:
        return cast(
            DatabaseQuery[Any, Any, Any],
            self._select_as(cast(Any, source), alias),
        )

    @overload  # type: ignore[override]
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.id"],
        operator: SchemaComparisonOperator,
        value: int,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.first_name", "first_name"],
        operator: SchemaComparisonOperator,
        value: str,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.last_name", "last_name"],
        operator: SchemaComparisonOperator,
        value: str | None,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.status", "status"],
        operator: SchemaComparisonOperator,
        value: Literal["active", "inactive"],
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        column: Literal["pet.id", "pet.owner_id", "owner_id"],
        operator: SchemaComparisonOperator,
        value: int,
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        column: Literal["pet.name", "name"],
        operator: SchemaComparisonOperator,
        value: str,
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        column: Literal["pet.species", "species"],
        operator: SchemaComparisonOperator,
        value: Literal["cat", "dog", "hamster"],
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self,
        column: Callable[[ExpressionBuilder[ColumnT]], Expression[bool]],
    ) -> DatabaseQuery[ColumnT, ResultKeyT, ResultValueT]: ...

    def where(  # pyright: ignore[reportIncompatibleMethodOverride]
        self,
        column: str | Callable[[ExpressionBuilder[ColumnT]], Expression[bool]],
        operator: SchemaComparisonOperator | None = None,
        value: object = None,
    ) -> DatabaseQuery[Any, Any, Any]:
        if callable(column):
            return cast(DatabaseQuery[Any, Any, Any], super().where(column))
        if operator is None:
            raise TypeError("where() requires an operator and value")
        return cast(
            DatabaseQuery[Any, Any, Any],
            super().where(cast(Any, column), operator, value),
        )

    @overload
    def inner_join(
        self,
        table: Literal["person"],
        left: ColumnT | PersonColumns,
        right: ColumnT | PersonColumns,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def inner_join(
        self,
        table: Literal["pet"],
        left: ColumnT | PetColumns,
        right: ColumnT | PetColumns,
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def inner_join(
        self,
        table: TableName,
        left: ColumnT | AllColumns,
        right: ColumnT | AllColumns,
    ) -> DatabaseQuery[Any, ResultKeyT, ResultValueT]: ...

    def inner_join(
        self, table: str, left: str, right: str
    ) -> DatabaseQuery[Any, Any, Any]:
        return cast(DatabaseQuery[Any, Any, Any], self._inner_join(table, left, right))


# Typed client. `Pysely.create(schema=...)` builds and returns this.
class DatabaseClient(Pysely["DatabaseSchema"]):
    @overload  # type: ignore[override]
    def select_from(
        self, table: Literal["person"]
    ) -> DatabaseQuery[PersonColumns, Never, Never]: ...

    @overload
    def select_from(
        self, table: Literal["pet"]
    ) -> DatabaseQuery[PetColumns, Never, Never]: ...

    @overload
    def select_from(self, table: TableName) -> DatabaseQuery[Any, Never, Never]: ...

    def select_from(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, table: str
    ) -> DatabaseQuery[Any, Never, Never]:
        return cast(
            DatabaseQuery[Any, Never, Never],
            DatabaseQuery(super().select_from(table)),
        )


# Schema class. Pass it to `Pysely.create`; its base names the client.
class DatabaseSchema(GeneratedSchema[DatabaseClient]):
    person: PersonTable
    pet: PetTable
