"""Generated by `pysely codegen`. Do not edit.

Regenerate with:

    pysely codegen schema.py --output docs/assets/examples/database.py
"""

from __future__ import annotations

from collections.abc import Callable
from datetime import date, datetime
from decimal import Decimal
from typing import (
    Any,
    Literal,
    LiteralString,
    Never,
    TypeAlias,
    TypeVar,
    cast,
    overload,
)

from schema import DatabaseSchema

from pysely import (
    Expression,
    ExpressionBuilder,
    Pysely,
    SchemaComparisonOperator,
    TypedSchemaQueryBuilder,
)
from pysely.dialect import Dialect

PersonColumns: TypeAlias = Literal[
    "person.id",
    "person.first_name",
    "person.last_name",
    "person.status",
    "person.verified",
    "person.created_at",
    "first_name",
    "last_name",
    "status",
    "verified",
    "created_at",
]
PetColumns: TypeAlias = Literal[
    "pet.id",
    "pet.owner_id",
    "pet.name",
    "pet.species",
    "pet.birth_date",
    "pet.weight_kg",
    "owner_id",
    "name",
    "species",
    "birth_date",
    "weight_kg",
]
TableName: TypeAlias = Literal["person", "pet"]
AllColumns: TypeAlias = PersonColumns | PetColumns
ColumnT = TypeVar("ColumnT", bound=str)
ResultKeyT = TypeVar("ResultKeyT", bound=str)
ResultValueT = TypeVar("ResultValueT")
AliasT = TypeVar("AliasT", bound=LiteralString | Literal[""])


class DatabaseQuery(
    TypedSchemaQueryBuilder[DatabaseSchema, ColumnT, dict[ResultKeyT, ResultValueT]]
):
    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.id"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns, ResultKeyT | Literal["id"], ResultValueT | int
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.first_name", "first_name"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns, ResultKeyT | Literal["first_name"], ResultValueT | str
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.last_name", "last_name"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns,
        ResultKeyT | Literal["last_name"],
        ResultValueT | str | None,
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.status", "status"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns,
        ResultKeyT | Literal["status"],
        ResultValueT | Literal["active", "inactive"],
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.verified", "verified"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns, ResultKeyT | Literal["verified"], ResultValueT | bool
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        selections: Literal["person.created_at", "created_at"],
    ) -> DatabaseQuery[
        ColumnT | PersonColumns,
        ResultKeyT | Literal["created_at"],
        ResultValueT | datetime,
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.id"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns, ResultKeyT | Literal["id"], ResultValueT | int
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.owner_id", "owner_id"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns, ResultKeyT | Literal["owner_id"], ResultValueT | int
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.name", "name"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns, ResultKeyT | Literal["name"], ResultValueT | str
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.species", "species"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns,
        ResultKeyT | Literal["species"],
        ResultValueT | Literal["cat", "dog", "hamster"],
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.birth_date", "birth_date"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns,
        ResultKeyT | Literal["birth_date"],
        ResultValueT | date | None,
    ]: ...

    @overload
    def select(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        selections: Literal["pet.weight_kg", "weight_kg"],
    ) -> DatabaseQuery[
        ColumnT | PetColumns,
        ResultKeyT | Literal["weight_kg"],
        ResultValueT | Decimal | None,
    ]: ...

    @overload
    def select(
        self, selections: ColumnT | list[ColumnT] | tuple[ColumnT, ...]
    ) -> DatabaseQuery[ColumnT, str, object]: ...

    def select(
        self, selections: str | list[Any] | tuple[str, ...]
    ) -> DatabaseQuery[Any, Any, Any]:
        return cast(DatabaseQuery[Any, Any, Any], super().select(cast(Any, selections)))

    @overload
    def select_as(
        self,
        source: Literal["person.id", "pet.id", "pet.owner_id", "owner_id"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | int]: ...

    @overload
    def select_as(
        self,
        source: Literal["person.first_name", "first_name", "pet.name", "name"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | str]: ...

    @overload
    def select_as(
        self,
        source: Literal["person.last_name", "last_name"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | str | None]: ...

    @overload
    def select_as(
        self,
        source: Literal["person.status", "status"],
        alias: AliasT,
    ) -> DatabaseQuery[
        ColumnT, ResultKeyT | AliasT, ResultValueT | Literal["active", "inactive"]
    ]: ...

    @overload
    def select_as(
        self,
        source: Literal["person.verified", "verified"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | bool]: ...

    @overload
    def select_as(
        self,
        source: Literal["person.created_at", "created_at"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | datetime]: ...

    @overload
    def select_as(
        self,
        source: Literal["pet.species", "species"],
        alias: AliasT,
    ) -> DatabaseQuery[
        ColumnT, ResultKeyT | AliasT, ResultValueT | Literal["cat", "dog", "hamster"]
    ]: ...

    @overload
    def select_as(
        self,
        source: Literal["pet.birth_date", "birth_date"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | date | None]: ...

    @overload
    def select_as(
        self,
        source: Literal["pet.weight_kg", "weight_kg"],
        alias: AliasT,
    ) -> DatabaseQuery[ColumnT, ResultKeyT | AliasT, ResultValueT | Decimal | None]: ...

    @overload
    def select_as(
        self, source: ColumnT, alias: str
    ) -> DatabaseQuery[ColumnT, str, object]: ...

    def select_as(self, source: str, alias: str) -> DatabaseQuery[Any, Any, Any]:
        return cast(
            DatabaseQuery[Any, Any, Any],
            self._select_as(cast(Any, source), alias),
        )

    @overload  # type: ignore[override]
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.id"],
        operator: SchemaComparisonOperator,
        value: int,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.first_name", "first_name"],
        operator: SchemaComparisonOperator,
        value: str,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.last_name", "last_name"],
        operator: SchemaComparisonOperator,
        value: str | None,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.status", "status"],
        operator: SchemaComparisonOperator,
        value: Literal["active", "inactive"],
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.verified", "verified"],
        operator: SchemaComparisonOperator,
        value: bool,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT],
        column: Literal["person.created_at", "created_at"],
        operator: SchemaComparisonOperator,
        value: datetime,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        column: Literal["pet.id", "pet.owner_id", "owner_id"],
        operator: SchemaComparisonOperator,
        value: int,
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        column: Literal["pet.name", "name"],
        operator: SchemaComparisonOperator,
        value: str,
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        column: Literal["pet.species", "species"],
        operator: SchemaComparisonOperator,
        value: Literal["cat", "dog", "hamster"],
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        column: Literal["pet.birth_date", "birth_date"],
        operator: SchemaComparisonOperator,
        value: date | None,
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self: DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT],
        column: Literal["pet.weight_kg", "weight_kg"],
        operator: SchemaComparisonOperator,
        value: Decimal | None,
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def where(
        self,
        column: Callable[[ExpressionBuilder[ColumnT]], Expression[bool]],
    ) -> DatabaseQuery[ColumnT, ResultKeyT, ResultValueT]: ...

    def where(  # pyright: ignore[reportIncompatibleMethodOverride]
        self,
        column: str | Callable[[ExpressionBuilder[ColumnT]], Expression[bool]],
        operator: SchemaComparisonOperator | None = None,
        value: object = None,
    ) -> DatabaseQuery[Any, Any, Any]:
        if callable(column):
            return cast(DatabaseQuery[Any, Any, Any], super().where(column))
        if operator is None:
            raise TypeError("where() requires an operator and value")
        return cast(
            DatabaseQuery[Any, Any, Any],
            super().where(cast(Any, column), operator, value),
        )

    @overload
    def inner_join(
        self,
        table: Literal["person"],
        left: ColumnT | PersonColumns,
        right: ColumnT | PersonColumns,
    ) -> DatabaseQuery[ColumnT | PersonColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def inner_join(
        self,
        table: Literal["pet"],
        left: ColumnT | PetColumns,
        right: ColumnT | PetColumns,
    ) -> DatabaseQuery[ColumnT | PetColumns, ResultKeyT, ResultValueT]: ...

    @overload
    def inner_join(
        self,
        table: TableName,
        left: ColumnT | AllColumns,
        right: ColumnT | AllColumns,
    ) -> DatabaseQuery[Any, ResultKeyT, ResultValueT]: ...

    def inner_join(
        self, table: str, left: str, right: str
    ) -> DatabaseQuery[Any, Any, Any]:
        return cast(DatabaseQuery[Any, Any, Any], self._inner_join(table, left, right))


class Database:
    def __init__(self, *, dialect: Dialect) -> None:
        self._client = Pysely(schema=DatabaseSchema, dialect=dialect)

    @overload
    def select_from(
        self, table: Literal["person"]
    ) -> DatabaseQuery[PersonColumns, Never, Never]: ...

    @overload
    def select_from(
        self, table: Literal["pet"]
    ) -> DatabaseQuery[PetColumns, Never, Never]: ...

    @overload
    def select_from(self, table: TableName) -> DatabaseQuery[Any, Never, Never]: ...

    def select_from(self, table: str) -> DatabaseQuery[Any, Never, Never]:
        return cast(
            DatabaseQuery[Any, Never, Never],
            DatabaseQuery(self._client.select_from(table)),
        )
