"""Generated by `pysely codegen` from docs/assets/examples/tables.py. Do not edit.

This module is your typed schema. Pass `schema` to `Database`:

    from pysely import Database
    from schema import schema

    db = Database(schema=schema, dialect=dialect)

Regenerate with:

    pysely codegen docs/assets/examples/tables.py \
        --output docs/assets/examples/schema.py
"""

# The typed classes overload every public method per column, so
# the checks below are noise for generated code.
# mypy: disable-error-code="override, overload-overlap"
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportOverlappingOverload=false

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import (
    TYPE_CHECKING,
    Any,
    Generic,
    Literal,
    LiteralString,
    Never,
    TypeAlias,
    TypeVar,
    cast,
    overload,
)

from pysely import (
    Cons,
    Expression,
    ExpressionBuilder,
    GeneratedSchema,
    Nil,
    OrderDirection,
    Pysely,
    TypedSchemaQueryBuilder,
)


# Table classes, copied from docs/assets/examples/tables.py.
class PersonTable:
    id: int
    first_name: str
    last_name: str | None
    status: Literal["active", "inactive"]


class PetTable:
    id: int
    owner_id: int
    name: str
    species: Literal["cat", "dog", "hamster"]


# XColumns: every spelling, valid while X is the only table in the
# query. XScope: the spellings that stay unambiguous after a join.
PersonColumns: TypeAlias = Literal[
    "person.id",
    "person.first_name",
    "person.last_name",
    "person.status",
    "id",
    "first_name",
    "last_name",
    "status",
]
PersonScope: TypeAlias = Literal[
    "person.id",
    "person.first_name",
    "person.last_name",
    "person.status",
    "first_name",
    "last_name",
    "status",
]
PetColumns: TypeAlias = Literal[
    "pet.id",
    "pet.owner_id",
    "pet.name",
    "pet.species",
    "id",
    "owner_id",
    "name",
    "species",
]
PetScope: TypeAlias = Literal[
    "pet.id",
    "pet.owner_id",
    "pet.name",
    "pet.species",
    "owner_id",
    "name",
    "species",
]
TableName: TypeAlias = Literal["person", "pet"]

# Query state: tables joined, columns in scope, tables joined
# nullably, selected fields (newest first), and whether a right or
# full join made every field nullable.
TableT = TypeVar("TableT", bound=str)
TablesT = TypeVar("TablesT", bound=str)
ColumnsT = TypeVar("ColumnsT", bound=str)
ColumnT = TypeVar("ColumnT", bound=str)
ScopeT = TypeVar("ScopeT", bound=str)
NullT = TypeVar("NullT", bound=str)
FieldsT = TypeVar("FieldsT")
StarT = TypeVar("StarT", bound=str)
AliasT = TypeVar("AliasT", bound=LiteralString | Literal[""])
# Positions in the selected-field list, for ordering by an alias.
RestT = TypeVar("RestT")
K1 = TypeVar("K1", bound=str)
K2 = TypeVar("K2", bound=str)
K3 = TypeVar("K3", bound=str)
K4 = TypeVar("K4", bound=str)
K5 = TypeVar("K5", bound=str)
K6 = TypeVar("K6", bound=str)
K7 = TypeVar("K7", bound=str)
K8 = TypeVar("K8", bound=str)
V1 = TypeVar("V1")
V2 = TypeVar("V2")
V3 = TypeVar("V3")
V4 = TypeVar("V4")
V5 = TypeVar("V5")
V6 = TypeVar("V6")
V7 = TypeVar("V7")
V8 = TypeVar("V8")

if TYPE_CHECKING:
    # Callback predicates get the same scope and value checks as a
    # flat where() call.
    class DatabaseExpressionBuilder(
        ExpressionBuilder[ColumnT], Generic[TablesT, ColumnT]
    ):
        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["person"], ColumnT],
            column: Literal["person.id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["person"], ColumnT],
            column: Literal["person.id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["person"], ColumnT],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["person"], ColumnT],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["person"], ColumnT],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["like", "not like"],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["person"], ColumnT],
            column: Literal["person.status", "status"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["active", "inactive"],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["person"], ColumnT],
            column: Literal["person.status", "status"],
            operator: Literal["in", "not in"],
            value: list[Literal["active", "inactive"]]
            | tuple[Literal["active", "inactive"], ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["person"], ColumnT],
            column: Literal["person.status", "status"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["person"], ColumnT],
            column: Literal[
                "person.id",
                "person.first_name",
                "first_name",
                "person.last_name",
                "last_name",
                "person.status",
                "status",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["pet"], ColumnT],
            column: Literal["pet.id", "pet.owner_id", "owner_id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["pet"], ColumnT],
            column: Literal["pet.id", "pet.owner_id", "owner_id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["pet"], ColumnT],
            column: Literal["pet.name", "name"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["pet"], ColumnT],
            column: Literal["pet.name", "name"],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["pet"], ColumnT],
            column: Literal["pet.name", "name"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["pet"], ColumnT],
            column: Literal["pet.species", "species"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["cat", "dog", "hamster"],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["pet"], ColumnT],
            column: Literal["pet.species", "species"],
            operator: Literal["in", "not in"],
            value: list[Literal["cat", "dog", "hamster"]]
            | tuple[Literal["cat", "dog", "hamster"], ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["pet"], ColumnT],
            column: Literal["pet.species", "species"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self: DatabaseExpressionBuilder[TablesT | Literal["pet"], ColumnT],
            column: Literal[
                "pet.id",
                "pet.owner_id",
                "owner_id",
                "pet.name",
                "name",
                "pet.species",
                "species",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> Expression[bool]: ...

        def __call__(self, column: Any, operator: Any, value: Any) -> Expression[bool]:
            return super().__call__(column, operator, value)

    class PersonExpressionBuilder(ExpressionBuilder[PersonColumns]):
        @overload
        def __call__(
            self,
            column: Literal["person.id", "id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["person.id", "id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["like", "not like"],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["person.status", "status"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["active", "inactive"],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["person.status", "status"],
            operator: Literal["in", "not in"],
            value: list[Literal["active", "inactive"]]
            | tuple[Literal["active", "inactive"], ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["person.status", "status"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal[
                "person.id",
                "id",
                "person.first_name",
                "first_name",
                "person.last_name",
                "last_name",
                "person.status",
                "status",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> Expression[bool]: ...

        def __call__(self, column: Any, operator: Any, value: Any) -> Expression[bool]:
            return super().__call__(column, operator, value)

    class PetExpressionBuilder(ExpressionBuilder[PetColumns]):
        @overload
        def __call__(
            self,
            column: Literal["pet.id", "id", "pet.owner_id", "owner_id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["pet.id", "id", "pet.owner_id", "owner_id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["pet.name", "name"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["pet.name", "name"],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["pet.name", "name"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["pet.species", "species"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["cat", "dog", "hamster"],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["pet.species", "species"],
            operator: Literal["in", "not in"],
            value: list[Literal["cat", "dog", "hamster"]]
            | tuple[Literal["cat", "dog", "hamster"], ...],
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal["pet.species", "species"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> Expression[bool]: ...

        @overload
        def __call__(
            self,
            column: Literal[
                "pet.id",
                "id",
                "pet.owner_id",
                "owner_id",
                "pet.name",
                "name",
                "pet.species",
                "species",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> Expression[bool]: ...

        def __call__(self, column: Any, operator: Any, value: Any) -> Expression[bool]:
            return super().__call__(column, operator, value)

    # Joined queries. One overload per column; the nullable form
    # comes first and only matches once its table is outer-joined.
    class DatabaseQuery(
        TypedSchemaQueryBuilder["DatabaseSchema", ColumnT, FieldsT, StarT],
        Generic[TablesT, ColumnT, NullT, FieldsT, StarT],
    ):
        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["person"],
                ColumnT,
                NullT | Literal["person"],
                FieldsT,
                StarT,
            ],
            selections: Literal["person.id"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT | Literal["person"],
            Cons[Literal["id"], int | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            selections: Literal["person.id"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT,
            Cons[Literal["id"], int, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["person"],
                ColumnT,
                NullT | Literal["person"],
                FieldsT,
                StarT,
            ],
            selections: Literal["person.first_name", "first_name"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT | Literal["person"],
            Cons[Literal["first_name"], str | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            selections: Literal["person.first_name", "first_name"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT,
            Cons[Literal["first_name"], str, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["person"],
                ColumnT,
                NullT | Literal["person"],
                FieldsT,
                StarT,
            ],
            selections: Literal["person.last_name", "last_name"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT | Literal["person"],
            Cons[Literal["last_name"], str | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            selections: Literal["person.last_name", "last_name"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT,
            Cons[Literal["last_name"], str | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["person"],
                ColumnT,
                NullT | Literal["person"],
                FieldsT,
                StarT,
            ],
            selections: Literal["person.status", "status"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT | Literal["person"],
            Cons[Literal["status"], Literal["active", "inactive"] | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            selections: Literal["person.status", "status"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT,
            Cons[Literal["status"], Literal["active", "inactive"], FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["pet"],
                ColumnT,
                NullT | Literal["pet"],
                FieldsT,
                StarT,
            ],
            selections: Literal["pet.id"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT | Literal["pet"],
            Cons[Literal["id"], int | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            selections: Literal["pet.id"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT,
            Cons[Literal["id"], int, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["pet"],
                ColumnT,
                NullT | Literal["pet"],
                FieldsT,
                StarT,
            ],
            selections: Literal["pet.owner_id", "owner_id"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT | Literal["pet"],
            Cons[Literal["owner_id"], int | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            selections: Literal["pet.owner_id", "owner_id"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT,
            Cons[Literal["owner_id"], int, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["pet"],
                ColumnT,
                NullT | Literal["pet"],
                FieldsT,
                StarT,
            ],
            selections: Literal["pet.name", "name"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT | Literal["pet"],
            Cons[Literal["name"], str | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            selections: Literal["pet.name", "name"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT,
            Cons[Literal["name"], str, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["pet"],
                ColumnT,
                NullT | Literal["pet"],
                FieldsT,
                StarT,
            ],
            selections: Literal["pet.species", "species"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT | Literal["pet"],
            Cons[Literal["species"], Literal["cat", "dog", "hamster"] | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            selections: Literal["pet.species", "species"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT,
            Cons[Literal["species"], Literal["cat", "dog", "hamster"], FieldsT],
            StarT,
        ]: ...

        @overload
        def select(
            self, selections: ColumnT | Sequence[ColumnT]
        ) -> DatabaseQuery[
            TablesT, ColumnT, NullT, Cons[str, object, FieldsT], StarT
        ]: ...

        def select(self, selections: Any) -> Any:
            return super().select(selections)

        # select_as: grouped by value type; the alias becomes a key.
        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["person"],
                ColumnT,
                NullT | Literal["person"],
                FieldsT,
                StarT,
            ],
            source: Literal["person.id"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT | Literal["person"],
            Cons[AliasT, int | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            source: Literal["person.id"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT,
            Cons[AliasT, int, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["person"],
                ColumnT,
                NullT | Literal["person"],
                FieldsT,
                StarT,
            ],
            source: Literal["person.first_name", "first_name"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT | Literal["person"],
            Cons[AliasT, str | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            source: Literal["person.first_name", "first_name"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT,
            Cons[AliasT, str, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["person"],
                ColumnT,
                NullT | Literal["person"],
                FieldsT,
                StarT,
            ],
            source: Literal["person.last_name", "last_name"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT | Literal["person"],
            Cons[AliasT, str | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            source: Literal["person.last_name", "last_name"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT,
            Cons[AliasT, str | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["person"],
                ColumnT,
                NullT | Literal["person"],
                FieldsT,
                StarT,
            ],
            source: Literal["person.status", "status"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT | Literal["person"],
            Cons[AliasT, Literal["active", "inactive"] | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            source: Literal["person.status", "status"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT,
            NullT,
            Cons[AliasT, Literal["active", "inactive"], FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["pet"],
                ColumnT,
                NullT | Literal["pet"],
                FieldsT,
                StarT,
            ],
            source: Literal["pet.id", "pet.owner_id", "owner_id"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT | Literal["pet"],
            Cons[AliasT, int | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            source: Literal["pet.id", "pet.owner_id", "owner_id"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, Cons[AliasT, int, FieldsT], StarT
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["pet"],
                ColumnT,
                NullT | Literal["pet"],
                FieldsT,
                StarT,
            ],
            source: Literal["pet.name", "name"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT | Literal["pet"],
            Cons[AliasT, str | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            source: Literal["pet.name", "name"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, Cons[AliasT, str, FieldsT], StarT
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["pet"],
                ColumnT,
                NullT | Literal["pet"],
                FieldsT,
                StarT,
            ],
            source: Literal["pet.species", "species"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT | Literal["pet"],
            Cons[AliasT, Literal["cat", "dog", "hamster"] | None, FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            source: Literal["pet.species", "species"],
            alias: AliasT,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT,
            NullT,
            Cons[AliasT, Literal["cat", "dog", "hamster"], FieldsT],
            StarT,
        ]: ...

        @overload
        def select_as(
            self, source: ColumnT, alias: str
        ) -> DatabaseQuery[
            TablesT, ColumnT, NullT, Cons[str, object, FieldsT], StarT
        ]: ...

        def select_as(self, source: Any, alias: str) -> Any:
            return self._select_as(source, alias)

        # where: operator families take different value shapes.
        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["like", "not like"],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.status", "status"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["active", "inactive"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.status", "status"],
            operator: Literal["in", "not in"],
            value: list[Literal["active", "inactive"]]
            | tuple[Literal["active", "inactive"], ...],
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.status", "status"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "person.id",
                "person.first_name",
                "first_name",
                "person.last_name",
                "last_name",
                "person.status",
                "status",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.id", "pet.owner_id", "owner_id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.id", "pet.owner_id", "owner_id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.name", "name"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.name", "name"],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.name", "name"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.species", "species"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["cat", "dog", "hamster"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.species", "species"],
            operator: Literal["in", "not in"],
            value: list[Literal["cat", "dog", "hamster"]]
            | tuple[Literal["cat", "dog", "hamster"], ...],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.species", "species"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "pet.id",
                "pet.owner_id",
                "owner_id",
                "pet.name",
                "name",
                "pet.species",
                "species",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def where(
            self,
            column: Callable[
                [DatabaseExpressionBuilder[TablesT, ColumnT]], Expression[bool]
            ],
        ) -> DatabaseQuery[TablesT, ColumnT, NullT, FieldsT, StarT]: ...

        def where(self, column: Any, operator: Any = None, value: Any = None) -> Any:
            if isinstance(column, str):
                name = cast(Any, column)
                return super().where(name, operator, value)
            return super().where(column)

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["like", "not like"],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.status", "status"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["active", "inactive"],
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.status", "status"],
            operator: Literal["in", "not in"],
            value: list[Literal["active", "inactive"]]
            | tuple[Literal["active", "inactive"], ...],
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["person.status", "status"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "person.id",
                "person.first_name",
                "first_name",
                "person.last_name",
                "last_name",
                "person.status",
                "status",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.id", "pet.owner_id", "owner_id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.id", "pet.owner_id", "owner_id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.name", "name"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.name", "name"],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.name", "name"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.species", "species"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["cat", "dog", "hamster"],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.species", "species"],
            operator: Literal["in", "not in"],
            value: list[Literal["cat", "dog", "hamster"]]
            | tuple[Literal["cat", "dog", "hamster"], ...],
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal["pet.species", "species"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self: DatabaseQuery[
                TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
            ],
            column: Literal[
                "pet.id",
                "pet.owner_id",
                "owner_id",
                "pet.name",
                "name",
                "pet.species",
                "species",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT, NullT, FieldsT, StarT
        ]: ...

        @overload
        def having(
            self,
            column: Callable[
                [DatabaseExpressionBuilder[TablesT, ColumnT]], Expression[bool]
            ],
        ) -> DatabaseQuery[TablesT, ColumnT, NullT, FieldsT, StarT]: ...

        def having(self, column: Any, operator: Any = None, value: Any = None) -> Any:
            return self._having(column, operator, value)

        @overload
        def order_by(
            self, column: ColumnT, direction: OrderDirection = "asc"
        ) -> DatabaseQuery[TablesT, ColumnT, NullT, FieldsT, StarT]: ...

        @overload
        def order_by(
            self: DatabaseQuery[TablesT, ColumnT, NullT, Cons[K1, V1, RestT], StarT],
            column: K1,
            direction: OrderDirection = "asc",
        ) -> DatabaseQuery[TablesT, ColumnT, NullT, Cons[K1, V1, RestT], StarT]: ...

        @overload
        def order_by(
            self: DatabaseQuery[
                TablesT, ColumnT, NullT, Cons[K1, V1, Cons[K2, V2, RestT]], StarT
            ],
            column: K2,
            direction: OrderDirection = "asc",
        ) -> DatabaseQuery[
            TablesT, ColumnT, NullT, Cons[K1, V1, Cons[K2, V2, RestT]], StarT
        ]: ...

        @overload
        def order_by(
            self: DatabaseQuery[
                TablesT,
                ColumnT,
                NullT,
                Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, RestT]]],
                StarT,
            ],
            column: K3,
            direction: OrderDirection = "asc",
        ) -> DatabaseQuery[
            TablesT,
            ColumnT,
            NullT,
            Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, RestT]]],
            StarT,
        ]: ...

        @overload
        def order_by(
            self: DatabaseQuery[
                TablesT,
                ColumnT,
                NullT,
                Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, RestT]]]],
                StarT,
            ],
            column: K4,
            direction: OrderDirection = "asc",
        ) -> DatabaseQuery[
            TablesT,
            ColumnT,
            NullT,
            Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, RestT]]]],
            StarT,
        ]: ...

        @overload
        def order_by(
            self: DatabaseQuery[
                TablesT,
                ColumnT,
                NullT,
                Cons[
                    K1,
                    V1,
                    Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, RestT]]]],
                ],
                StarT,
            ],
            column: K5,
            direction: OrderDirection = "asc",
        ) -> DatabaseQuery[
            TablesT,
            ColumnT,
            NullT,
            Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, RestT]]]]],
            StarT,
        ]: ...

        @overload
        def order_by(
            self: DatabaseQuery[
                TablesT,
                ColumnT,
                NullT,
                Cons[
                    K1,
                    V1,
                    Cons[
                        K2,
                        V2,
                        Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, Cons[K6, V6, RestT]]]],
                    ],
                ],
                StarT,
            ],
            column: K6,
            direction: OrderDirection = "asc",
        ) -> DatabaseQuery[
            TablesT,
            ColumnT,
            NullT,
            Cons[
                K1,
                V1,
                Cons[
                    K2,
                    V2,
                    Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, Cons[K6, V6, RestT]]]],
                ],
            ],
            StarT,
        ]: ...

        @overload
        def order_by(
            self: DatabaseQuery[
                TablesT,
                ColumnT,
                NullT,
                Cons[
                    K1,
                    V1,
                    Cons[
                        K2,
                        V2,
                        Cons[
                            K3,
                            V3,
                            Cons[
                                K4, V4, Cons[K5, V5, Cons[K6, V6, Cons[K7, V7, RestT]]]
                            ],
                        ],
                    ],
                ],
                StarT,
            ],
            column: K7,
            direction: OrderDirection = "asc",
        ) -> DatabaseQuery[
            TablesT,
            ColumnT,
            NullT,
            Cons[
                K1,
                V1,
                Cons[
                    K2,
                    V2,
                    Cons[
                        K3,
                        V3,
                        Cons[K4, V4, Cons[K5, V5, Cons[K6, V6, Cons[K7, V7, RestT]]]],
                    ],
                ],
            ],
            StarT,
        ]: ...

        @overload
        def order_by(
            self: DatabaseQuery[
                TablesT,
                ColumnT,
                NullT,
                Cons[
                    K1,
                    V1,
                    Cons[
                        K2,
                        V2,
                        Cons[
                            K3,
                            V3,
                            Cons[
                                K4,
                                V4,
                                Cons[
                                    K5,
                                    V5,
                                    Cons[K6, V6, Cons[K7, V7, Cons[K8, V8, RestT]]],
                                ],
                            ],
                        ],
                    ],
                ],
                StarT,
            ],
            column: K8,
            direction: OrderDirection = "asc",
        ) -> DatabaseQuery[
            TablesT,
            ColumnT,
            NullT,
            Cons[
                K1,
                V1,
                Cons[
                    K2,
                    V2,
                    Cons[
                        K3,
                        V3,
                        Cons[
                            K4,
                            V4,
                            Cons[
                                K5, V5, Cons[K6, V6, Cons[K7, V7, Cons[K8, V8, RestT]]]
                            ],
                        ],
                    ],
                ],
            ],
            StarT,
        ]: ...

        def order_by(self, column: Any, direction: Any = "asc") -> Any:
            return self._order_by(column, direction)

        # joins: the ON columns may use the prior scope and the new
        # table. Outer joins record which side may be missing.
        @overload
        def inner_join(
            self,
            table: Literal["person"],
            left: ColumnT | PersonScope,
            right: ColumnT | PersonScope,
        ) -> DatabaseQuery[
            TablesT | Literal["person"], ColumnT | PersonScope, NullT, FieldsT, StarT
        ]: ...

        @overload
        def inner_join(
            self,
            table: Literal["pet"],
            left: ColumnT | PetScope,
            right: ColumnT | PetScope,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT | PetScope, NullT, FieldsT, StarT
        ]: ...

        def inner_join(self, table: Any, left: Any, right: Any) -> Any:
            return self._join("inner", table, left, right)

        @overload
        def left_join(
            self,
            table: Literal["person"],
            left: ColumnT | PersonScope,
            right: ColumnT | PersonScope,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT | PersonScope,
            NullT | Literal["person"],
            FieldsT,
            StarT,
        ]: ...

        @overload
        def left_join(
            self,
            table: Literal["pet"],
            left: ColumnT | PetScope,
            right: ColumnT | PetScope,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT | PetScope,
            NullT | Literal["pet"],
            FieldsT,
            StarT,
        ]: ...

        def left_join(self, table: Any, left: Any, right: Any) -> Any:
            return self._join("left", table, left, right)

        @overload
        def right_join(
            self,
            table: Literal["person"],
            left: ColumnT | PersonScope,
            right: ColumnT | PersonScope,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT | PersonScope,
            NullT,
            FieldsT,
            Literal["*"],
        ]: ...

        @overload
        def right_join(
            self,
            table: Literal["pet"],
            left: ColumnT | PetScope,
            right: ColumnT | PetScope,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"], ColumnT | PetScope, NullT, FieldsT, Literal["*"]
        ]: ...

        def right_join(self, table: Any, left: Any, right: Any) -> Any:
            return self._join("right", table, left, right)

        @overload
        def full_join(
            self,
            table: Literal["person"],
            left: ColumnT | PersonScope,
            right: ColumnT | PersonScope,
        ) -> DatabaseQuery[
            TablesT | Literal["person"],
            ColumnT | PersonScope,
            NullT | Literal["person"],
            FieldsT,
            Literal["*"],
        ]: ...

        @overload
        def full_join(
            self,
            table: Literal["pet"],
            left: ColumnT | PetScope,
            right: ColumnT | PetScope,
        ) -> DatabaseQuery[
            TablesT | Literal["pet"],
            ColumnT | PetScope,
            NullT | Literal["pet"],
            FieldsT,
            Literal["*"],
        ]: ...

        def full_join(self, table: Any, left: Any, right: Any) -> Any:
            return self._join("full", table, left, right)

    # Single-table queries. Each table gets its own class so the
    # editor only weighs that table's overloads; joins move to
    # DatabaseQuery.
    class SingleTableQuery(
        TypedSchemaQueryBuilder["DatabaseSchema", ColumnsT, FieldsT, Never],
        Generic[TableT, ColumnsT, ScopeT, FieldsT],
    ):
        @overload
        def inner_join(
            self,
            table: Literal["person"],
            left: ScopeT | PersonScope,
            right: ScopeT | PersonScope,
        ) -> DatabaseQuery[
            TableT | Literal["person"], ScopeT | PersonScope, Never, FieldsT, Never
        ]: ...

        @overload
        def inner_join(
            self,
            table: Literal["pet"],
            left: ScopeT | PetScope,
            right: ScopeT | PetScope,
        ) -> DatabaseQuery[
            TableT | Literal["pet"], ScopeT | PetScope, Never, FieldsT, Never
        ]: ...

        def inner_join(self, table: Any, left: Any, right: Any) -> Any:
            query = self._query.join("inner", table, left, right)
            joined: DatabaseQuery[Any, Any, Any, Any, Any] = DatabaseQuery(
                cast(Any, query.typed(DatabaseExpressionBuilder))
            )
            return joined

        @overload
        def left_join(
            self,
            table: Literal["person"],
            left: ScopeT | PersonScope,
            right: ScopeT | PersonScope,
        ) -> DatabaseQuery[
            TableT | Literal["person"],
            ScopeT | PersonScope,
            Literal["person"],
            FieldsT,
            Never,
        ]: ...

        @overload
        def left_join(
            self,
            table: Literal["pet"],
            left: ScopeT | PetScope,
            right: ScopeT | PetScope,
        ) -> DatabaseQuery[
            TableT | Literal["pet"], ScopeT | PetScope, Literal["pet"], FieldsT, Never
        ]: ...

        def left_join(self, table: Any, left: Any, right: Any) -> Any:
            query = self._query.join("left", table, left, right)
            joined: DatabaseQuery[Any, Any, Any, Any, Any] = DatabaseQuery(
                cast(Any, query.typed(DatabaseExpressionBuilder))
            )
            return joined

        @overload
        def right_join(
            self,
            table: Literal["person"],
            left: ScopeT | PersonScope,
            right: ScopeT | PersonScope,
        ) -> DatabaseQuery[
            TableT | Literal["person"],
            ScopeT | PersonScope,
            Never,
            FieldsT,
            Literal["*"],
        ]: ...

        @overload
        def right_join(
            self,
            table: Literal["pet"],
            left: ScopeT | PetScope,
            right: ScopeT | PetScope,
        ) -> DatabaseQuery[
            TableT | Literal["pet"], ScopeT | PetScope, Never, FieldsT, Literal["*"]
        ]: ...

        def right_join(self, table: Any, left: Any, right: Any) -> Any:
            query = self._query.join("right", table, left, right)
            joined: DatabaseQuery[Any, Any, Any, Any, Any] = DatabaseQuery(
                cast(Any, query.typed(DatabaseExpressionBuilder))
            )
            return joined

        @overload
        def full_join(
            self,
            table: Literal["person"],
            left: ScopeT | PersonScope,
            right: ScopeT | PersonScope,
        ) -> DatabaseQuery[
            TableT | Literal["person"],
            ScopeT | PersonScope,
            Literal["person"],
            FieldsT,
            Literal["*"],
        ]: ...

        @overload
        def full_join(
            self,
            table: Literal["pet"],
            left: ScopeT | PetScope,
            right: ScopeT | PetScope,
        ) -> DatabaseQuery[
            TableT | Literal["pet"],
            ScopeT | PetScope,
            Literal["pet"],
            FieldsT,
            Literal["*"],
        ]: ...

        def full_join(self, table: Any, left: Any, right: Any) -> Any:
            query = self._query.join("full", table, left, right)
            joined: DatabaseQuery[Any, Any, Any, Any, Any] = DatabaseQuery(
                cast(Any, query.typed(DatabaseExpressionBuilder))
            )
            return joined

    class PersonQuery(
        SingleTableQuery[Literal["person"], PersonColumns, PersonScope, FieldsT],
        Generic[FieldsT],
    ):
        @overload
        def select(
            self, selections: Literal["person.id", "id"]
        ) -> PersonQuery[Cons[Literal["id"], int, FieldsT]]: ...

        @overload
        def select(
            self, selections: Literal["person.first_name", "first_name"]
        ) -> PersonQuery[Cons[Literal["first_name"], str, FieldsT]]: ...

        @overload
        def select(
            self, selections: Literal["person.last_name", "last_name"]
        ) -> PersonQuery[Cons[Literal["last_name"], str | None, FieldsT]]: ...

        @overload
        def select(
            self, selections: Literal["person.status", "status"]
        ) -> PersonQuery[
            Cons[Literal["status"], Literal["active", "inactive"], FieldsT]
        ]: ...

        @overload
        def select(
            self, selections: PersonColumns | Sequence[PersonColumns]
        ) -> PersonQuery[Cons[str, object, FieldsT]]: ...

        def select(self, selections: Any) -> Any:
            return super().select(selections)

        @overload
        def select_as(
            self, source: Literal["person.id", "id"], alias: AliasT
        ) -> PersonQuery[Cons[AliasT, int, FieldsT]]: ...

        @overload
        def select_as(
            self, source: Literal["person.first_name", "first_name"], alias: AliasT
        ) -> PersonQuery[Cons[AliasT, str, FieldsT]]: ...

        @overload
        def select_as(
            self, source: Literal["person.last_name", "last_name"], alias: AliasT
        ) -> PersonQuery[Cons[AliasT, str | None, FieldsT]]: ...

        @overload
        def select_as(
            self, source: Literal["person.status", "status"], alias: AliasT
        ) -> PersonQuery[Cons[AliasT, Literal["active", "inactive"], FieldsT]]: ...

        @overload
        def select_as(
            self, source: PersonColumns, alias: str
        ) -> PersonQuery[Cons[str, object, FieldsT]]: ...

        def select_as(self, source: Any, alias: str) -> Any:
            return self._select_as(source, alias)

        @overload
        def where(
            self,
            column: Literal["person.id", "id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["person.id", "id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["like", "not like"],
            value: str,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["person.status", "status"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["active", "inactive"],
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["person.status", "status"],
            operator: Literal["in", "not in"],
            value: list[Literal["active", "inactive"]]
            | tuple[Literal["active", "inactive"], ...],
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["person.status", "status"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal[
                "person.id",
                "id",
                "person.first_name",
                "first_name",
                "person.last_name",
                "last_name",
                "person.status",
                "status",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def where(
            self, column: Callable[[PersonExpressionBuilder], Expression[bool]]
        ) -> PersonQuery[FieldsT]: ...

        def where(self, column: Any, operator: Any = None, value: Any = None) -> Any:
            if isinstance(column, str):
                name = cast(Any, column)
                return super().where(name, operator, value)
            return super().where(column)

        @overload
        def having(
            self: PersonQuery[FieldsT],
            column: Literal["person.id", "id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def having(
            self: PersonQuery[FieldsT],
            column: Literal["person.id", "id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def having(
            self: PersonQuery[FieldsT],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def having(
            self: PersonQuery[FieldsT],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def having(
            self: PersonQuery[FieldsT],
            column: Literal[
                "person.first_name", "first_name", "person.last_name", "last_name"
            ],
            operator: Literal["like", "not like"],
            value: str,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def having(
            self: PersonQuery[FieldsT],
            column: Literal["person.status", "status"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["active", "inactive"],
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def having(
            self: PersonQuery[FieldsT],
            column: Literal["person.status", "status"],
            operator: Literal["in", "not in"],
            value: list[Literal["active", "inactive"]]
            | tuple[Literal["active", "inactive"], ...],
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def having(
            self: PersonQuery[FieldsT],
            column: Literal["person.status", "status"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def having(
            self: PersonQuery[FieldsT],
            column: Literal[
                "person.id",
                "id",
                "person.first_name",
                "first_name",
                "person.last_name",
                "last_name",
                "person.status",
                "status",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def having(
            self, column: Callable[[PersonExpressionBuilder], Expression[bool]]
        ) -> PersonQuery[FieldsT]: ...

        def having(self, column: Any, operator: Any = None, value: Any = None) -> Any:
            return self._having(column, operator, value)

        @overload
        def order_by(
            self, column: PersonColumns, direction: OrderDirection = "asc"
        ) -> PersonQuery[FieldsT]: ...

        @overload
        def order_by(
            self: PersonQuery[Cons[K1, V1, RestT]],
            column: K1,
            direction: OrderDirection = "asc",
        ) -> PersonQuery[Cons[K1, V1, RestT]]: ...

        @overload
        def order_by(
            self: PersonQuery[Cons[K1, V1, Cons[K2, V2, RestT]]],
            column: K2,
            direction: OrderDirection = "asc",
        ) -> PersonQuery[Cons[K1, V1, Cons[K2, V2, RestT]]]: ...

        @overload
        def order_by(
            self: PersonQuery[Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, RestT]]]],
            column: K3,
            direction: OrderDirection = "asc",
        ) -> PersonQuery[Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, RestT]]]]: ...

        @overload
        def order_by(
            self: PersonQuery[
                Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, RestT]]]]
            ],
            column: K4,
            direction: OrderDirection = "asc",
        ) -> PersonQuery[
            Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, RestT]]]]
        ]: ...

        @overload
        def order_by(
            self: PersonQuery[
                Cons[
                    K1,
                    V1,
                    Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, RestT]]]],
                ],
            ],
            column: K5,
            direction: OrderDirection = "asc",
        ) -> PersonQuery[
            Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, RestT]]]]]
        ]: ...

        @overload
        def order_by(
            self: PersonQuery[
                Cons[
                    K1,
                    V1,
                    Cons[
                        K2,
                        V2,
                        Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, Cons[K6, V6, RestT]]]],
                    ],
                ],
            ],
            column: K6,
            direction: OrderDirection = "asc",
        ) -> PersonQuery[
            Cons[
                K1,
                V1,
                Cons[
                    K2,
                    V2,
                    Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, Cons[K6, V6, RestT]]]],
                ],
            ],
        ]: ...

        @overload
        def order_by(
            self: PersonQuery[
                Cons[
                    K1,
                    V1,
                    Cons[
                        K2,
                        V2,
                        Cons[
                            K3,
                            V3,
                            Cons[
                                K4, V4, Cons[K5, V5, Cons[K6, V6, Cons[K7, V7, RestT]]]
                            ],
                        ],
                    ],
                ],
            ],
            column: K7,
            direction: OrderDirection = "asc",
        ) -> PersonQuery[
            Cons[
                K1,
                V1,
                Cons[
                    K2,
                    V2,
                    Cons[
                        K3,
                        V3,
                        Cons[K4, V4, Cons[K5, V5, Cons[K6, V6, Cons[K7, V7, RestT]]]],
                    ],
                ],
            ],
        ]: ...

        @overload
        def order_by(
            self: PersonQuery[
                Cons[
                    K1,
                    V1,
                    Cons[
                        K2,
                        V2,
                        Cons[
                            K3,
                            V3,
                            Cons[
                                K4,
                                V4,
                                Cons[
                                    K5,
                                    V5,
                                    Cons[K6, V6, Cons[K7, V7, Cons[K8, V8, RestT]]],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            column: K8,
            direction: OrderDirection = "asc",
        ) -> PersonQuery[
            Cons[
                K1,
                V1,
                Cons[
                    K2,
                    V2,
                    Cons[
                        K3,
                        V3,
                        Cons[
                            K4,
                            V4,
                            Cons[
                                K5, V5, Cons[K6, V6, Cons[K7, V7, Cons[K8, V8, RestT]]]
                            ],
                        ],
                    ],
                ],
            ],
        ]: ...

        def order_by(self, column: Any, direction: Any = "asc") -> Any:
            return self._order_by(column, direction)

    class PetQuery(
        SingleTableQuery[Literal["pet"], PetColumns, PetScope, FieldsT],
        Generic[FieldsT],
    ):
        @overload
        def select(
            self, selections: Literal["pet.id", "id"]
        ) -> PetQuery[Cons[Literal["id"], int, FieldsT]]: ...

        @overload
        def select(
            self, selections: Literal["pet.owner_id", "owner_id"]
        ) -> PetQuery[Cons[Literal["owner_id"], int, FieldsT]]: ...

        @overload
        def select(
            self, selections: Literal["pet.name", "name"]
        ) -> PetQuery[Cons[Literal["name"], str, FieldsT]]: ...

        @overload
        def select(
            self, selections: Literal["pet.species", "species"]
        ) -> PetQuery[
            Cons[Literal["species"], Literal["cat", "dog", "hamster"], FieldsT]
        ]: ...

        @overload
        def select(
            self, selections: PetColumns | Sequence[PetColumns]
        ) -> PetQuery[Cons[str, object, FieldsT]]: ...

        def select(self, selections: Any) -> Any:
            return super().select(selections)

        @overload
        def select_as(
            self,
            source: Literal["pet.id", "id", "pet.owner_id", "owner_id"],
            alias: AliasT,
        ) -> PetQuery[Cons[AliasT, int, FieldsT]]: ...

        @overload
        def select_as(
            self, source: Literal["pet.name", "name"], alias: AliasT
        ) -> PetQuery[Cons[AliasT, str, FieldsT]]: ...

        @overload
        def select_as(
            self, source: Literal["pet.species", "species"], alias: AliasT
        ) -> PetQuery[Cons[AliasT, Literal["cat", "dog", "hamster"], FieldsT]]: ...

        @overload
        def select_as(
            self, source: PetColumns, alias: str
        ) -> PetQuery[Cons[str, object, FieldsT]]: ...

        def select_as(self, source: Any, alias: str) -> Any:
            return self._select_as(source, alias)

        @overload
        def where(
            self,
            column: Literal["pet.id", "id", "pet.owner_id", "owner_id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["pet.id", "id", "pet.owner_id", "owner_id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> PetQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["pet.name", "name"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["pet.name", "name"],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> PetQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["pet.name", "name"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["pet.species", "species"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["cat", "dog", "hamster"],
        ) -> PetQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["pet.species", "species"],
            operator: Literal["in", "not in"],
            value: list[Literal["cat", "dog", "hamster"]]
            | tuple[Literal["cat", "dog", "hamster"], ...],
        ) -> PetQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal["pet.species", "species"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def where(
            self,
            column: Literal[
                "pet.id",
                "id",
                "pet.owner_id",
                "owner_id",
                "pet.name",
                "name",
                "pet.species",
                "species",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def where(
            self, column: Callable[[PetExpressionBuilder], Expression[bool]]
        ) -> PetQuery[FieldsT]: ...

        def where(self, column: Any, operator: Any = None, value: Any = None) -> Any:
            if isinstance(column, str):
                name = cast(Any, column)
                return super().where(name, operator, value)
            return super().where(column)

        @overload
        def having(
            self: PetQuery[FieldsT],
            column: Literal["pet.id", "id", "pet.owner_id", "owner_id"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: int,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def having(
            self: PetQuery[FieldsT],
            column: Literal["pet.id", "id", "pet.owner_id", "owner_id"],
            operator: Literal["in", "not in"],
            value: list[int] | tuple[int, ...],
        ) -> PetQuery[FieldsT]: ...

        @overload
        def having(
            self: PetQuery[FieldsT],
            column: Literal["pet.name", "name"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: str,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def having(
            self: PetQuery[FieldsT],
            column: Literal["pet.name", "name"],
            operator: Literal["in", "not in"],
            value: list[str] | tuple[str, ...],
        ) -> PetQuery[FieldsT]: ...

        @overload
        def having(
            self: PetQuery[FieldsT],
            column: Literal["pet.name", "name"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def having(
            self: PetQuery[FieldsT],
            column: Literal["pet.species", "species"],
            operator: Literal["=", "!=", "<>", "<", "<=", ">", ">="],
            value: Literal["cat", "dog", "hamster"],
        ) -> PetQuery[FieldsT]: ...

        @overload
        def having(
            self: PetQuery[FieldsT],
            column: Literal["pet.species", "species"],
            operator: Literal["in", "not in"],
            value: list[Literal["cat", "dog", "hamster"]]
            | tuple[Literal["cat", "dog", "hamster"], ...],
        ) -> PetQuery[FieldsT]: ...

        @overload
        def having(
            self: PetQuery[FieldsT],
            column: Literal["pet.species", "species"],
            operator: Literal["like", "not like"],
            value: str,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def having(
            self: PetQuery[FieldsT],
            column: Literal[
                "pet.id",
                "id",
                "pet.owner_id",
                "owner_id",
                "pet.name",
                "name",
                "pet.species",
                "species",
            ],
            operator: Literal["is", "is not"],
            value: None,
        ) -> PetQuery[FieldsT]: ...

        @overload
        def having(
            self, column: Callable[[PetExpressionBuilder], Expression[bool]]
        ) -> PetQuery[FieldsT]: ...

        def having(self, column: Any, operator: Any = None, value: Any = None) -> Any:
            return self._having(column, operator, value)

        @overload
        def order_by(
            self, column: PetColumns, direction: OrderDirection = "asc"
        ) -> PetQuery[FieldsT]: ...

        @overload
        def order_by(
            self: PetQuery[Cons[K1, V1, RestT]],
            column: K1,
            direction: OrderDirection = "asc",
        ) -> PetQuery[Cons[K1, V1, RestT]]: ...

        @overload
        def order_by(
            self: PetQuery[Cons[K1, V1, Cons[K2, V2, RestT]]],
            column: K2,
            direction: OrderDirection = "asc",
        ) -> PetQuery[Cons[K1, V1, Cons[K2, V2, RestT]]]: ...

        @overload
        def order_by(
            self: PetQuery[Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, RestT]]]],
            column: K3,
            direction: OrderDirection = "asc",
        ) -> PetQuery[Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, RestT]]]]: ...

        @overload
        def order_by(
            self: PetQuery[
                Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, RestT]]]]
            ],
            column: K4,
            direction: OrderDirection = "asc",
        ) -> PetQuery[
            Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, RestT]]]]
        ]: ...

        @overload
        def order_by(
            self: PetQuery[
                Cons[
                    K1,
                    V1,
                    Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, RestT]]]],
                ],
            ],
            column: K5,
            direction: OrderDirection = "asc",
        ) -> PetQuery[
            Cons[K1, V1, Cons[K2, V2, Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, RestT]]]]]
        ]: ...

        @overload
        def order_by(
            self: PetQuery[
                Cons[
                    K1,
                    V1,
                    Cons[
                        K2,
                        V2,
                        Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, Cons[K6, V6, RestT]]]],
                    ],
                ],
            ],
            column: K6,
            direction: OrderDirection = "asc",
        ) -> PetQuery[
            Cons[
                K1,
                V1,
                Cons[
                    K2,
                    V2,
                    Cons[K3, V3, Cons[K4, V4, Cons[K5, V5, Cons[K6, V6, RestT]]]],
                ],
            ],
        ]: ...

        @overload
        def order_by(
            self: PetQuery[
                Cons[
                    K1,
                    V1,
                    Cons[
                        K2,
                        V2,
                        Cons[
                            K3,
                            V3,
                            Cons[
                                K4, V4, Cons[K5, V5, Cons[K6, V6, Cons[K7, V7, RestT]]]
                            ],
                        ],
                    ],
                ],
            ],
            column: K7,
            direction: OrderDirection = "asc",
        ) -> PetQuery[
            Cons[
                K1,
                V1,
                Cons[
                    K2,
                    V2,
                    Cons[
                        K3,
                        V3,
                        Cons[K4, V4, Cons[K5, V5, Cons[K6, V6, Cons[K7, V7, RestT]]]],
                    ],
                ],
            ],
        ]: ...

        @overload
        def order_by(
            self: PetQuery[
                Cons[
                    K1,
                    V1,
                    Cons[
                        K2,
                        V2,
                        Cons[
                            K3,
                            V3,
                            Cons[
                                K4,
                                V4,
                                Cons[
                                    K5,
                                    V5,
                                    Cons[K6, V6, Cons[K7, V7, Cons[K8, V8, RestT]]],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            column: K8,
            direction: OrderDirection = "asc",
        ) -> PetQuery[
            Cons[
                K1,
                V1,
                Cons[
                    K2,
                    V2,
                    Cons[
                        K3,
                        V3,
                        Cons[
                            K4,
                            V4,
                            Cons[
                                K5, V5, Cons[K6, V6, Cons[K7, V7, Cons[K8, V8, RestT]]]
                            ],
                        ],
                    ],
                ],
            ],
        ]: ...

        def order_by(self, column: Any, direction: Any = "asc") -> Any:
            return self._order_by(column, direction)

    # Typed client. `Database(schema=...)` builds and returns this.
    class DatabaseClient(Pysely["DatabaseSchema"]):
        @overload
        def select_from(self, table: Literal["person"]) -> PersonQuery[Nil]: ...

        @overload
        def select_from(self, table: Literal["pet"]) -> PetQuery[Nil]: ...

        def select_from(self, table: str) -> Any:
            query_class, builder = _QUERIES[table]
            query = super().select_from(table).typed(builder)
            return query_class(cast(Any, query))

else:
    # Runtime twins of the typed classes: no overloads, so importing
    # this module costs the same for any schema size.
    class DatabaseExpressionBuilder(ExpressionBuilder):
        pass

    class DatabaseQuery(TypedSchemaQueryBuilder):
        def select_as(self, source, alias):
            return self._select_as(source, alias)

        def having(self, column, operator=None, value=None):
            return self._having(column, operator, value)

        def order_by(self, column, direction="asc"):
            return self._order_by(column, direction)

        def inner_join(self, table, left, right):
            return self._join("inner", table, left, right)

        def left_join(self, table, left, right):
            return self._join("left", table, left, right)

        def right_join(self, table, left, right):
            return self._join("right", table, left, right)

        def full_join(self, table, left, right):
            return self._join("full", table, left, right)

    class SingleTableQuery(TypedSchemaQueryBuilder):
        def select_as(self, source, alias):
            return self._select_as(source, alias)

        def having(self, column, operator=None, value=None):
            return self._having(column, operator, value)

        def order_by(self, column, direction="asc"):
            return self._order_by(column, direction)

        def inner_join(self, table, left, right):
            query = self._query.join("inner", table, left, right)
            return DatabaseQuery(query.typed(DatabaseExpressionBuilder))

        def left_join(self, table, left, right):
            query = self._query.join("left", table, left, right)
            return DatabaseQuery(query.typed(DatabaseExpressionBuilder))

        def right_join(self, table, left, right):
            query = self._query.join("right", table, left, right)
            return DatabaseQuery(query.typed(DatabaseExpressionBuilder))

        def full_join(self, table, left, right):
            query = self._query.join("full", table, left, right)
            return DatabaseQuery(query.typed(DatabaseExpressionBuilder))

    class PersonExpressionBuilder(ExpressionBuilder):
        pass

    class PersonQuery(SingleTableQuery):
        pass

    class PetExpressionBuilder(ExpressionBuilder):
        pass

    class PetQuery(SingleTableQuery):
        pass

    class DatabaseClient(Pysely):
        def select_from(self, table):
            query_class, builder = _QUERIES[table]
            query = super().select_from(table).typed(builder)
            return query_class(query)


# The query and expression-builder classes behind each table name.
_QUERIES: dict[str, tuple[type[Any], type[Any]]] = {
    "person": (PersonQuery, PersonExpressionBuilder),
    "pet": (PetQuery, PetExpressionBuilder),
}


# Schema class. Pass it to `Database`; its base names the client.
class DatabaseSchema(GeneratedSchema[DatabaseClient]):
    person: PersonTable
    pet: PetTable


schema = DatabaseSchema
