"""Write src/pysely/row.py: the typed result row.

A row's static type is a cons list of (key, value) fields built up by
``select``/``select_as``. ``__getitem__`` looks a key up positionally: one
overload per depth, the newest field first. That keeps the generated schema
module free of per-key row code and gives every schema the same row class.

    uv run python scripts/generate_row.py
"""

from __future__ import annotations

from pathlib import Path

# Pyright matches nested type arguments about 18 levels deep; beyond that a
# lookup silently degrades to Unknown, so the typed depth stays under it.
DEPTH = 16
OUTPUT = Path(__file__).parents[1] / "src/pysely/row.py"

HEADER = '''"""Typed result rows. Generated by scripts/generate_row.py; do not edit."""

# The per-depth overloads narrow Mapping's key type on purpose.
# pyright: reportIncompatibleMethodOverride=false, reportOverlappingOverload=false
# mypy: disable-error-code="override, overload-overlap"

from __future__ import annotations

from collections.abc import Iterator, Mapping
from typing import Any, Generic, Literal, TypeVar, overload

K = TypeVar("K", bound=str)
V = TypeVar("V")
R = TypeVar("R")
FieldsT = TypeVar("FieldsT")
StarT = TypeVar("StarT", bound=str)


class Nil:
    """The fields of a query that has selected nothing yet."""


class Cons(Generic[K, V, R]):
    """One selected field (key, value type) in front of the fields before it."""


class Row(Mapping[str, object], Generic[FieldsT, StarT]):
    """An immutable result row addressed by output column name.

    ``FieldsT`` lists the selected fields newest first; ``StarT`` is
    ``Literal["*"]`` once a right or full join has made every key nullable.
    Lookups are typed for the first {depth} fields; beyond that a key reads as
    ``object``. The overloads reject unknown keys, which also means checkers do
    not see the row as a plain ``Mapping[str, ...]`` for ``dict(row)`` or
    ``**row``; use ``row.to_dict()``.
    """

    __slots__ = ("_data",)

    def __init__(self, data: Mapping[str, object]) -> None:
        self._data: dict[str, object] = dict(data)

'''

FOOTER = """
    def __iter__(self) -> Iterator[str]:
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)

    def to_dict(self) -> dict[str, object]:
        return dict(self._data)

    def __repr__(self) -> str:
        return f"{type(self).__name__}({self._data!r})"
"""


def pattern(depth: int) -> str:
    """``Cons[Any, Any, ... Cons[K, V, Any]]`` with the match ``depth`` deep."""
    inner = "Cons[K, V, Any]"
    for _ in range(depth - 1):
        inner = f"Cons[Any, Any, {inner}]"
    return inner


def deeper_than(depth: int) -> str:
    inner = "Any"
    for _ in range(depth + 1):
        inner = f"Cons[Any, Any, {inner}]"
    return inner


def method(name: str, returns: str, star_returns: str, fallback: str) -> list[str]:
    lines: list[str] = []
    for depth in range(1, DEPTH + 1):
        shape = pattern(depth)
        lines += [
            "    @overload",
            f"    def {name}(",
            f'        self: Row[{shape}, Literal["*"]], key: K',
            f"    ) -> {star_returns}: ...",
            "",
            "    @overload",
            f"    def {name}(self: Row[{shape}, StarT], key: K) -> {returns}: ...",
            "",
        ]
    lines += [
        f"    # More than {DEPTH} fields: later keys are looked up at runtime only.",
        "    @overload",
        f"    def {name}(self: Row[{deeper_than(DEPTH)}, StarT], key: str)"
        f" -> {fallback}: ...",
        "",
    ]
    return lines


def main() -> None:
    lines = [HEADER.format(depth=DEPTH)]
    lines += method("__getitem__", "V", "V | None", "object")
    lines += [
        "    def __getitem__(self, key: Any) -> Any:",
        "        return self._data[key]",
        "",
    ]
    lines += method("get", "V | None", "V | None", "object")
    lines += [
        "    @overload",
        "    def get(self, key: str, default: object = None) -> object: ...",
        "",
        "    def get(self, key: Any, default: Any = None) -> Any:",
        "        return self._data.get(key, default)",
    ]
    lines.append(FOOTER)
    OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
