"""Generate the shared flat-row stub, independent of any database schema."""

from pathlib import Path

DEPTH = 64


def render() -> str:
    lines = [
        '"""Generated by scripts/generate_flat_row.py. Do not edit."""',
        "",
        "# ruff: noqa: E501, I001",
        "# fmt: off",
        '# mypy: disable-error-code="override, overload-overlap"',
        "# pyright: reportIncompatibleMethodOverride=false",
        "# pyright: reportOverlappingOverload=false",
        "from collections.abc import Iterator, Mapping",
        "from typing import Any, Generic, Literal, TypeVar, TypeVarTuple, overload",
        'K = TypeVar("K", bound=str)',
        'V = TypeVar("V")',
        'D = TypeVar("D")',
        'StarT = TypeVar("StarT", bound=str)',
        'FieldsT = TypeVarTuple("FieldsT")',
        'RestT = TypeVarTuple("RestT")',
        "class Field(Generic[K, V]): ...",
        "class FlatRow(Mapping[str, object], Generic[StarT, *FieldsT]):",
        "    def __init__(self, data: Mapping[str, object]) -> None: ...",
    ]
    for method in ("__getitem__", "get"):
        for depth in range(DEPTH):
            fields = ", ".join([*(["Any"] * depth), "Field[K, V]", "*RestT"])
            for star, value in [('Literal["*"]', "V | None"), ("StarT", "V")]:
                default = ", default: D = ..." if method == "get" else ""
                result = "V | D | None" if method == "get" else value
                lines.extend(
                    [
                        "    @overload",
                        f"    def {method}(self: FlatRow[{star}, {fields}], "
                        f"key: K{default}) -> {result}: ...",
                    ]
                )
    lines.extend(
        [
            "    @overload",
            "    def get(self, key: str, default: object = None) -> object: ...",
            "    def __iter__(self) -> Iterator[str]: ...",
            "    def __len__(self) -> int: ...",
            "    def to_dict(self) -> dict[str, object]: ...",
        ]
    )
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    path = Path(__file__).parents[1] / "src/pysely/flat_row.pyi"
    path.write_text(render())
